##### Import Statements
The cell below contains the import statements for required libraries.

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Load initial datasets
Load all the initial datasets and view them.

In [2]:
crop_df = pd.read_csv('district-wise-climate-and-crop-data-of-nepal/NepalAgriStats_Cereal.csv')
climate_df = pd.read_csv('district-wise-climate-and-crop-data-of-nepal/climate_data.csv')

In [3]:
crop_df

,DISTRICT_CODE,DISTRICT_NAME,PD_P_197980,PD_P_198081,PD_P_198182,PD_P_198283,PD_P_198384,PD_P_198485,PD_P_198586,PD_P_198687,...,BW_P_201213,BW_P_201314,BW_A_201011,BW_A_201112,BW_A_201213,BW_A_201314,BW_Y_201011,BW_Y_201112,BW_Y_201213,BW_Y_201314
0,1,Taplejung,3320,3400,3570,3010,3070,3190,3800,3610,...,165,170,0,155.0,118,120,0.00,1096.77,1398,1416.67
1,2,Panchthar,7180,7000,5680,3810,14350,17440,18390,17600,...,36,36,60,60.0,56,56,700.00,700.00,643,642.86
2,3,Ilam,18700,27530,30290,15840,20040,27270,24950,21340,...,17,20,28,28.0,25,25,714.29,714.29,680,800.00
3,4,Jhapa,148020,152250,137070,126570,160820,143380,153100,147380,...,1265,1270,1300,1300.0,1265,1270,1000.00,1000.00,1000,1000.00
4,5,Sankhuwasabha,20260,18480,18480,14310,15870,21270,22240,20500,...,10,15,0,20.0,18,18,0.00,550.00,556,833.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,71,Kailali,32670,86700,73790,58680,75600,71050,70490,72000,...,25,25,0,25.0,25,25,0.00,1000.00,1000,1000.00
71,72,Darchula,2380,2190,2300,2210,2580,2190,5180,4840,...,80,82,107,100.0,100,100,799.07,850.00,800,820.00
72,73,Baitadi,3910,6570,6600,6270,5940,5040,3780,4240,...,0,0,0,0.0,0,0,0.00,0.00,0,0.00
73,74,Dadeldhura,1710,3600,3450,8630,5760,7390,7280,6920,...,0,0,0,0.0,0,0,0.00,0.00,0,0.00
74,75,Kanchanpur,16930,43660,55000,44240,77150,73900,74970,60840,...,0,0,0,0.0,0,0,0.00,0.00,0,0.00

The above dataset contains the area, production and yield of 75 districts of Nepal from the fiscal year 1979/80 (i.e. 1979 July 16) to the fiscal year 2013/14 (i.e. 2014 July 15).<br>
<br>
Below is the code for the columms of this dataset.
<br>
| Product	| ProductCode | StatsType | StatsDescription |
|-----------|-------------|-----------|------------------|
| Paddy	 	|	PD		  | P, A, Y	  | Production(mt), Area(ha), Yield(kg/ha) |
| Wheat	 	|	WT		  | P, A, Y	  | Production(mt), Area(ha), Yield(kg/ha) |
| Maize	 	|	MZ		  | P, A, Y	  | Production(mt), Area(ha), Yield(kg/ha) |
| Millet	|	ML		  | P, A, Y	  | Production(mt), Area(ha), Yield(kg/ha) |
| Barley	|	BL		  | P, A, Y	  | Production(mt), Area(ha), Yield(kg/ha) |
| Buckwheat	|	BW		  | P, A, Y	  | Production(mt), Area(ha), Yield(kg/ha) |

e.g. PD_P_201213: Paddy production in fiscal year 2012/13.

In [4]:
# pd.set_option('display.max_columns', None)
climate_df

,DATE,DISTRICT,LAT,LON,PRECTOT,PS,QV2M,RH2M,T2M,T2MWET,...,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
0,1/1/1981,Arghakhanchi,27.9,83.2,0.00,93.51,4.81,45.41,13.89,2.15,...,10.89,11.32,1.89,3.83,0.69,3.14,2.41,4.12,0.73,3.39
1,1/2/1981,Arghakhanchi,27.9,83.2,0.00,93.59,4.94,46.78,13.84,2.54,...,11.17,11.44,1.72,2.60,1.09,1.50,2.25,3.30,0.96,2.34
2,1/3/1981,Arghakhanchi,27.9,83.2,0.03,93.55,5.22,47.91,14.33,3.32,...,9.93,12.24,1.80,2.80,0.48,2.32,2.32,3.54,0.39,3.15
3,1/4/1981,Arghakhanchi,27.9,83.2,0.02,93.49,5.36,50.83,13.82,3.73,...,10.41,12.17,2.18,3.54,1.06,2.49,2.90,4.05,0.93,3.12
4,1/5/1981,Arghakhanchi,27.9,83.2,1.84,93.49,5.84,55.55,13.76,4.93,...,10.53,12.32,1.96,2.70,0.69,2.02,2.74,4.64,0.96,3.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883123,12/27/2019,Udayapur,26.9,86.5,0.00,95.52,4.72,54.60,11.13,2.17,...,11.01,9.73,2.38,4.20,1.25,2.94,3.40,4.57,1.37,3.20
883124,12/28/2019,Udayapur,26.9,86.5,0.00,95.73,4.23,50.90,10.56,0.60,...,13.18,9.07,2.03,2.52,1.07,1.45,3.05,4.51,1.44,3.07
883125,12/29/2019,Udayapur,26.9,86.5,0.00,95.76,4.08,46.09,11.51,0.18,...,12.30,9.12,2.01,3.01,0.85,2.17,2.97,4.12,0.94,3.18
883126,12/30/2019,Udayapur,26.9,86.5,0.00,95.84,4.44,47.07,12.47,1.32,...,12.20,9.76,1.44,1.94,0.27,1.67,2.00,3.22,0.15,3.06
883127,12/31/2019,Udayapur,26.9,86.5,0.00,95.93,5.43,49.68,14.77,3.89,...,11.68,11.67,1.59,3.22,0.45,2.78,2.02,3.43,0.66,2.77

In [5]:
display("Number of districts in climate data: "+str(len(climate_df['DISTRICT'].unique())))
display("Number of districts in crop data: "+str(len(crop_df['DISTRICT_NAME'].unique())))

'Number of districts in climate data: 62'

'Number of districts in crop data: 75'

The climate dataset contains the various climate data of 62 districts of Nepal which is 13 less than the number of districts that the crop dataset contains. The dataset contains data from the year 1981 to 2019 of the 62 districts.<br>
<br>
Below is the code for the columns of the dataset:
<br>
   |             |                                                     |
   |-------------|-----------------------------------------------------|
   | PRECTOT     | MERRA2 1/2x1/2 Precipitation (mm day-1)             |
   | PS          | MERRA2 1/2x1/2 Surface Pressure (kPa)               |
   | QV2M        | MERRA2 1/2x1/2 Specific Humidity at 2 Meters (g/kg) |
   | RH2M        | MERRA2 1/2x1/2 Relative Humidity at 2 Meters (%)    |
   | T2M         | MERRA2 1/2x1/2 Temperature at 2 Meters (C)          |
   | T2MWET      | MERRA2 1/2x1/2 Wet Bulb Temperature at 2 Meters (C) |
   | T2M_MAX     | MERRA2 1/2x1/2 Maximum Temperature at 2 Meters (C)  |
   | T2M_MIN     | MERRA2 1/2x1/2 Minimum Temperature at 2 Meters (C)  |
   | T2M_RANGE   | MERRA2 1/2x1/2 Temperature Range at 2 Meters (C)    |
   | TS          | MERRA2 1/2x1/2 Earth Skin Temperature (C)           |
   | WS10M       | MERRA2 1/2x1/2 Wind Speed at 10 Meters (m/s)        | 
   | WS10M_MAX   | MERRA2 1/2x1/2 Maximum Wind Speed at 10 Meters (m/s)|
   | WS10M_MIN   | MERRA2 1/2x1/2 Minimum Wind Speed at 10 Meters (m/s)|
   | WS10M_RANGE | MERRA2 1/2x1/2 Wind Speed Range at 10 Meters (m/s)  |
   | WS50M       | MERRA2 1/2x1/2 Wind Speed at 50 Meters (m/s)        |
   | WS50M_MAX   | MERRA2 1/2x1/2 Maximum Wind Speed at 50 Meters (m/s)|
   | WS50M_MIN   | MERRA2 1/2x1/2 Minimum Wind Speed at 50 Meters (m/s)|
   | WS50M_RANGE | MERRA2 1/2x1/2 Wind Speed Range at 50 Meters (m/s)  |

Note: Before January 2018 the precipitation is reported as an accumulation, after it is in average rate.<br>

## Modifying climate dataset
Some of the names of districts in the crop data and climate data are incosistent. So, they are made consistent with each other below:

In [6]:
climate_df['DISTRICT'] = climate_df['DISTRICT'].replace('Panchther', 'Panchthar')
climate_df['DISTRICT'] = climate_df['DISTRICT'].replace('Terhathum', 'Tehrathum')
climate_df['DISTRICT'] = climate_df['DISTRICT'].replace('Dolkha', 'Dolakha')
climate_df['DISTRICT'] = climate_df['DISTRICT'].replace('Kabhre', 'Kavre')
climate_df['DISTRICT'] = climate_df['DISTRICT'].replace('Routahat', 'Rautahat')
climate_df['DISTRICT'] = climate_df['DISTRICT'].replace('Chitawan', 'Chitwan')
climate_df['DISTRICT'] = climate_df['DISTRICT'].replace('Tanahun', 'Tanahu')
climate_df['DISTRICT'] = climate_df['DISTRICT'].replace('Bajang', 'Bajhang')
display(climate_df['DISTRICT'].unique())

array(['Arghakhanchi', 'Baglung', 'Baitadi', 'Bajhang', 'Banke', 'Bara',
       'Bardiya', 'Bhaktapur', 'Chitwan', 'Dadeldhura', 'Dailekh', 'Dang',
       'Darchula', 'Dhading', 'Dhankuta', 'Dhanusa', 'Dolakha', 'Dolpa',
       'Doti', 'Gorkha', 'Gulmi', 'Humla', 'Ilam', 'Jhapa', 'Jumla',
       'Kavre', 'Kailali', 'Kanchanpur', 'Kaski', 'Kathmandu', 'Lalitpur',
       'Lamjung', 'Mahottari', 'Makwanpur', 'Manang', 'Morang', 'Mugu',
       'Mustang', 'Myagdi', 'Nawalparasi', 'Nuwakot', 'Okhaldhunga',
       'Palpa', 'Panchthar', 'Parbat', 'Rasuwa', 'Rautahat', 'Rukum',
       'Rupandehi', 'Salyan', 'Sankhuwasabha', 'Saptari', 'Sarlahi',
       'Sindhuli', 'Solukhumbu', 'Sunsari', 'Surkhet', 'Syangja',
       'Tanahu', 'Taplejung', 'Tehrathum', 'Udayapur'], dtype=object)

Let's see which districts are missing from the climate dataset below.

In [7]:
climate_districts = climate_df['DISTRICT'].unique()
crop_districts = crop_df['DISTRICT_NAME'].unique()
display("No. of climate districts: "+str(len(climate_districts)))
display("No. of crop districts: "+str(len(crop_districts)))
display("No. of missing districts: "+str(len(crop_districts) - len(climate_districts)))
missing_districts = [i for i in crop_districts if i not in climate_districts]
display("The missing districts are:")
display(missing_districts)

'No. of climate districts: 62'

'No. of crop districts: 75'

'No. of missing districts: 13'

'The missing districts are:'

['Bhojpur',
 'Khotang',
 'Siraha',
 'Ramechhap',
 'Sindhupalchok',
 'Parsa',
 'Kapilbastu',
 'Kalikot',
 'Rolpa',
 'Pyuthan',
 'Jajarkot',
 'Bajura',
 'Achham']

The data for the missing districts contains the data from 1982 but the climate data contains data from 1981. Since we are about to add the data of missing districts to the climate data, lets remove all the data from the year 1981 from the climate data.

In [8]:
climate_df.DATE = pd.to_datetime(climate_df.DATE) #Convert into a datetime value
climate_df.drop(climate_df[climate_df['DATE'].dt.year == 1981].index, inplace=True) #Drop all rows of the year 1981
climate_df

,DATE,DISTRICT,LAT,LON,PRECTOT,PS,QV2M,RH2M,T2M,T2MWET,...,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
365,1982-01-01,Arghakhanchi,27.9,83.2,0.00,93.66,4.15,40.01,13.58,0.17,...,11.23,11.19,1.99,4.69,0.43,4.26,2.57,5.12,0.34,4.78
366,1982-01-02,Arghakhanchi,27.9,83.2,0.00,93.48,4.17,43.36,12.42,0.19,...,13.66,9.92,1.92,3.53,0.85,2.67,2.34,3.55,1.16,2.39
367,1982-01-03,Arghakhanchi,27.9,83.2,0.00,93.53,4.32,41.00,13.81,0.64,...,12.38,11.02,1.69,2.85,0.45,2.40,2.09,3.24,0.60,2.64
368,1982-01-04,Arghakhanchi,27.9,83.2,0.00,93.75,4.61,38.58,15.81,1.65,...,12.32,13.38,1.78,2.88,0.45,2.43,2.28,3.48,0.54,2.94
369,1982-01-05,Arghakhanchi,27.9,83.2,0.01,93.75,6.87,58.37,15.53,6.88,...,8.92,13.59,2.39,3.97,0.94,3.03,3.54,4.75,1.41,3.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883123,2019-12-27,Udayapur,26.9,86.5,0.00,95.52,4.72,54.60,11.13,2.17,...,11.01,9.73,2.38,4.20,1.25,2.94,3.40,4.57,1.37,3.20
883124,2019-12-28,Udayapur,26.9,86.5,0.00,95.73,4.23,50.90,10.56,0.60,...,13.18,9.07,2.03,2.52,1.07,1.45,3.05,4.51,1.44,3.07
883125,2019-12-29,Udayapur,26.9,86.5,0.00,95.76,4.08,46.09,11.51,0.18,...,12.30,9.12,2.01,3.01,0.85,2.17,2.97,4.12,0.94,3.18
883126,2019-12-30,Udayapur,26.9,86.5,0.00,95.84,4.44,47.07,12.47,1.32,...,12.20,9.76,1.44,1.94,0.27,1.67,2.00,3.22,0.15,3.06
883127,2019-12-31,Udayapur,26.9,86.5,0.00,95.93,5.43,49.68,14.77,3.89,...,11.68,11.67,1.59,3.22,0.45,2.78,2.02,3.43,0.66,2.77

The climate_data for all missing districts have been extracted from https://power.larc.nasa.gov/data-access-viewer/.<br>
The dataset for one of the missing districts looks like below.

In [9]:
bhojpur_df = pd.read_csv('missing_districts/bhojpur.csv')
bhojpur_df

,YEAR,MO,DY,T2M,T2MWET,TS,T2M_RANGE,T2M_MAX,T2M_MIN,QV2M,...,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,LAT,LON
0,1982,1,1,12.35,6.32,9.66,-262.74,19.31,8.90,4.27,...,1.97,4.94,0.08,4.87,2.27,4.96,0.16,4.80,27.18,87.07
1,1982,1,2,12.01,5.70,9.41,-261.77,18.73,7.35,4.03,...,1.88,4.88,0.34,4.54,2.02,4.45,0.41,4.03,27.18,87.07
2,1982,1,3,12.80,6.24,10.02,-261.51,19.51,7.87,4.15,...,1.66,4.24,0.15,4.09,1.81,3.76,0.16,3.59,27.18,87.07
3,1982,1,4,14.73,8.08,12.08,-262.60,21.30,10.73,4.70,...,1.74,4.51,0.22,4.30,1.95,4.31,0.17,4.13,27.18,87.07
4,1982,1,5,15.12,8.93,12.83,-261.00,22.44,10.28,5.19,...,1.91,5.50,0.11,5.39,2.31,5.91,0.13,5.77,27.18,87.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13874,2019,12,27,9.78,5.18,7.48,-262.73,16.36,5.94,4.46,...,2.07,4.48,0.07,4.40,2.45,4.44,0.21,4.23,27.18,87.07
13875,2019,12,28,9.67,4.08,6.96,-261.27,16.98,5.10,3.85,...,1.68,3.48,0.20,3.28,1.92,3.00,0.49,2.52,27.18,87.07
13876,2019,12,29,11.51,5.01,7.61,-262.69,18.30,7.84,3.85,...,1.71,3.55,0.59,2.96,1.93,3.30,0.67,2.62,27.18,87.07
13877,2019,12,30,12.48,6.19,8.35,-263.58,18.54,8.97,4.21,...,1.66,2.96,0.75,2.22,1.85,2.69,1.02,1.66,27.18,87.07
13878,2019,12,31,13.45,7.84,9.52,-263.59,19.55,9.99,5.13,...,1.70,3.51,0.34,3.17,1.94,3.35,0.49,2.86,27.18,87.07

We can see that the above dataset is not consistent with the climate dataset. So, some processing needs to be done before combining this dataset with the climate dataset.<br>
Lets make a funtion for that below.

In [10]:
def process_missing_dataset(df, climate_df):
    df.rename(columns = {'MO':'MONTH', 'DY':'DAY', 'PRECTOTCORR':'PRECTOT'}, inplace=True) #rename columns 'MO' to 'MONTH' and 'DY' to 'DAY' and 'PRECTOTCORR to 'PRECTOT'
    df['DATE'] = pd.to_datetime(df[['YEAR', 'MONTH', 'DAY']]) #combine the 'YEAR', 'MONTH', 'DAY' columns into a single 'DATE' column
    df.drop(columns=['YEAR', 'MONTH', 'DAY'], inplace=True) #drop the 'YEAR', 'MONTH', 'DAY' columns
    df['T2M_RANGE'] = df['T2M_MAX'] - df['T2M_MIN'] #correct the temperature range column
    climate_df = pd.concat([climate_df, df], axis=0) #Combine the missing dataset with the climate dataset.
    return climate_df

Now, lets add all the missing data to the climate data.

In [11]:
for missing_district in missing_districts:
    missing_df = pd.read_csv(f'missing_districts/{missing_district.lower()}.csv')
    missing_df['DISTRICT'] = missing_district
    climate_df = process_missing_dataset(missing_df, climate_df)
climate_df.sort_values(by=['DISTRICT', 'DATE'], ascending=[True, True], inplace=True)
climate_df

,DATE,DISTRICT,LAT,LON,PRECTOT,PS,QV2M,RH2M,T2M,T2MWET,...,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
0,1982-01-01,Achham,29.11,81.3,0.00,87.90,3.17,34.44,11.54,3.64,...,13.41,7.57,1.84,3.98,0.38,3.61,2.09,3.95,0.47,3.48
1,1982-01-02,Achham,29.11,81.3,0.00,87.72,3.23,33.88,12.14,4.04,...,15.75,8.43,2.15,3.77,0.23,3.53,2.49,3.74,0.24,3.50
2,1982-01-03,Achham,29.11,81.3,0.01,87.79,3.42,34.44,12.51,4.49,...,13.92,9.12,1.96,3.96,0.33,3.63,2.27,4.02,0.38,3.64
3,1982-01-04,Achham,29.11,81.3,0.27,88.07,4.58,43.94,13.36,6.81,...,11.54,11.57,1.71,3.61,0.66,2.95,2.11,3.66,0.88,2.77
4,1982-01-05,Achham,29.11,81.3,0.43,88.11,6.47,65.56,12.36,8.98,...,11.49,11.44,2.00,3.59,0.97,2.62,2.69,4.05,1.09,2.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883123,2019-12-27,Udayapur,26.90,86.5,0.00,95.52,4.72,54.60,11.13,2.17,...,11.01,9.73,2.38,4.20,1.25,2.94,3.40,4.57,1.37,3.20
883124,2019-12-28,Udayapur,26.90,86.5,0.00,95.73,4.23,50.90,10.56,0.60,...,13.18,9.07,2.03,2.52,1.07,1.45,3.05,4.51,1.44,3.07
883125,2019-12-29,Udayapur,26.90,86.5,0.00,95.76,4.08,46.09,11.51,0.18,...,12.30,9.12,2.01,3.01,0.85,2.17,2.97,4.12,0.94,3.18
883126,2019-12-30,Udayapur,26.90,86.5,0.00,95.84,4.44,47.07,12.47,1.32,...,12.20,9.76,1.44,1.94,0.27,1.67,2.00,3.22,0.15,3.06
883127,2019-12-31,Udayapur,26.90,86.5,0.00,95.93,5.43,49.68,14.77,3.89,...,11.68,11.67,1.59,3.22,0.45,2.78,2.02,3.43,0.66,2.77

In [12]:
climate_df.isnull().values.any()

False

In [13]:
0 in climate_df.values

True

Now, lets convert this daily data to fiscal yearly data because the crop data that we have is in fiscal year.<br>
A fiscal year in Nepal starts from July 16 and ends in July 15 of next year.

In [14]:
climate_df['YEAR'] = climate_df.DATE.dt.year #make a new 'YEAR' column and set the value to the corresponding year from the 'DATE' column
climate_df.loc[(climate_df.DATE.dt.month > 7) |
               ((climate_df.DATE.dt.month == 7) &
                (climate_df.DATE.dt.day > 15)), 'YEAR'] += 1 #if date is above July 15, increase the value in year column by 1.
climate_df = climate_df[climate_df['DATE'] >= pd.to_datetime('1982-07-16')] #drop all data before 1982-07-16
climate_df = climate_df[climate_df['DATE'] <= pd.to_datetime('2019-07-15')] #drop all data after 2019-07-15
climate_df.YEAR = (climate_df.YEAR - 1).astype(str) + '/' + (climate_df.YEAR).astype(str) #modify the 'YEAR' column so that it represents fiscal year instead of regular year
climate_df.reset_index(drop=True, inplace=True) #reset the index numbering and start from 0
climate_df

,DATE,DISTRICT,LAT,LON,PRECTOT,PS,QV2M,RH2M,T2M,T2MWET,...,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,YEAR
0,1982-07-16,Achham,29.11,81.3,0.58,87.07,16.17,67.62,26.16,22.71,...,27.52,2.47,4.62,0.68,3.95,2.70,4.59,1.02,3.57,1982/1983
1,1982-07-17,Achham,29.11,81.3,0.00,86.82,15.81,61.62,27.62,23.24,...,29.17,2.41,4.47,0.59,3.88,2.90,4.53,0.98,3.56,1982/1983
2,1982-07-18,Achham,29.11,81.3,0.46,86.73,15.08,52.81,29.65,23.87,...,31.34,2.52,4.88,0.78,4.09,2.96,4.87,1.02,3.85,1982/1983
3,1982-07-19,Achham,29.11,81.3,4.76,86.96,16.78,66.19,27.33,23.57,...,28.95,2.84,6.05,0.17,5.88,3.09,6.26,0.24,6.02,1982/1983
4,1982-07-20,Achham,29.11,81.3,3.52,87.19,16.66,72.56,25.44,22.62,...,26.62,3.02,5.46,0.73,4.73,3.70,5.89,1.06,4.83,1982/1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1013545,2019-07-11,Udayapur,26.90,86.5,70.53,94.23,19.88,88.78,25.94,23.88,...,26.15,2.30,3.60,1.45,2.15,3.19,4.17,2.20,1.98,2018/2019
1013546,2019-07-12,Udayapur,26.90,86.5,61.51,94.28,20.34,92.16,25.71,24.27,...,25.80,3.31,4.45,1.89,2.56,4.44,5.36,2.74,2.62,2018/2019
1013547,2019-07-13,Udayapur,26.90,86.5,44.67,94.25,20.56,91.93,25.92,24.42,...,25.95,3.17,5.38,0.53,4.84,4.40,7.28,0.96,6.32,2018/2019
1013548,2019-07-14,Udayapur,26.90,86.5,31.92,93.99,21.14,90.57,26.59,24.87,...,26.49,4.91,6.26,3.37,2.89,6.84,8.91,4.87,4.04,2018/2019
1013549,2019-07-15,Udayapur,26.90,86.5,20.07,94.05,21.18,87.06,27.31,24.87,...,27.43,3.43,5.64,1.65,3.99,4.87,6.58,3.10,3.49,2018/2019

Let's calculate the mean, maximum and minimum of each column. We can then drop the columns we don't need and keep the columns we need.

In [15]:
climate_df.drop(columns=['DATE'], inplace=True) #remove the 'DATE' column because it is no longer needed
climate_df = climate_df.groupby(['YEAR', 'DISTRICT']).agg(['mean', 'min', 'max', 'sum']) #calculate the mean, min and max for each district for each fiscal year
climate_df.columns = ['_'.join(col).strip() for col in climate_df.columns.values] #flatten multicolumns
pd.set_option('display.max_columns', None)
climate_df

                        LAT_mean  LAT_min  LAT_max   LAT_sum  LON_mean  \
YEAR      DISTRICT
1982/1983 Achham           29.11    29.11    29.11  10625.15      81.3
          Arghakhanchi     27.90    27.90    27.90  10183.50      83.2
          Baglung          28.30    28.30    28.30  10329.50      83.6
          Baitadi          29.50    29.50    29.50  10767.50      80.5
          Bajhang          29.60    29.60    29.60  10804.00      81.2
...                          ...      ...      ...       ...       ...
2018/2019 Syangja          28.00    28.00    28.00  10220.00      83.8
          Tanahu           28.00    28.00    28.00  10220.00      84.1
          Taplejung        27.40    27.40    27.40  10001.00      87.7
          Tehrathum        27.10    27.10    27.10   9891.50      87.5
          Udayapur         26.90    26.90    26.90   9818.50      86.5

                        LON_min  LON_max  LON_sum  PRECTOT_mean  PRECTOT_min  \
YEAR      DISTRICT
1982/1983 Achham           81.3     81.3  29674.5      1.822329          0.0
          Arghakhanchi     83.2     83.2  30368.0      2.219534          0.0
          Baglung          83.6     83.6  30514.0      1.922000          0.0
          Baitadi          80.5     80.5  29382.5      1.365315          0.0
          Bajhang          81.2     81.2  29638.0      1.133726          0.0
...                         ...      ...      ...           ...          ...
2018/2019 Syangja          83.8     83.8  30587.0      4.368575          0.0
          Tanahu           84.1     84.1  30696.5      4.189151          0.0
          Taplejung        87.7     87.7  32010.5      3.762986          0.0
          Tehrathum        87.5     87.5  31937.5      3.762986          0.0
          Udayapur         86.5     86.5  31572.5      3.395918          0.0

                        PRECTOT_max  PRECTOT_sum    PS_mean  PS_min  PS_max  \
YEAR      DISTRICT
1982/1983 Achham              36.72       665.15  87.577863   86.73   88.40
          Arghakhanchi        71.40       810.13  93.133123   92.00   94.18
          Baglung             43.36       701.53  79.262877   78.66   79.89
          Baitadi             39.32       498.34  73.814658   73.28   74.43
          Bajhang             30.95       413.81  67.878877   67.16   68.47
...                             ...          ...        ...     ...     ...
2018/2019 Syangja             41.86      1594.53  86.005945   85.04   86.82
          Tanahu              35.95      1529.04  77.660274   76.92   78.25
          Taplejung           61.24      1373.49  80.040219   79.32   80.66
          Tehrathum           61.24      1373.49  80.040219   79.32   80.66
          Udayapur            70.53      1239.51  95.006329   93.87   96.00

                          PS_sum  QV2M_mean  QV2M_min  QV2M_max  QV2M_sum  \
YEAR      DISTRICT
1982/1983 Achham        31965.92   7.857616      1.53     18.55   2868.03
          Arghakhanchi  33993.59   8.912356      1.39     19.77   3253.01
          Baglung       28930.95   7.262740      1.33     16.04   2650.90
          Baitadi       26942.35   5.931178      1.31     14.56   2164.88
          Bajhang       24775.79   5.163945      1.01     12.74   1884.84
...                          ...        ...       ...       ...       ...
2018/2019 Syangja       31392.17   9.939973      2.82     18.98   3628.09
          Tanahu        28346.00   8.610411      1.97     16.24   3142.80
          Taplejung     29214.68   9.461699      2.56     16.66   3453.52
          Tehrathum     29214.68   9.461699      2.56     16.66   3453.52
          Udayapur      34677.31  11.662301      3.58     21.18   4256.74

                        RH2M_mean  RH2M_min  RH2M_max  RH2M_sum   T2M_mean  \
YEAR      DISTRICT
1982/1983 Achham        47.294082     11.00     90.81  17262.34  19.098575
          Arghakhanchi  45.122137      7.27     91.94  16469.58  22.478137
          Baglung       53.903781     12.15     96.24  19674.88  13.294795
          Baitadi       52.656329     17.08     91.64  19219.56   9.178027
          Bajhang       56.509452     20.24     90.50  20625.95   4.649507
...                           ...       ...       ...       ...        ...
2018/2019 Syangja       62.634192     25.64     96.88  22861.48  17.612219
          Tanahu        69.434959     33.77    100.00  25343.76  11.862795
          Taplejung     70.148384     32.18     98.73  25604.16  13.748740
          Tehrathum     70.148384     32.18     98.73  25604.16  13.748740
          Udayapur      56.259452     20.72     92.20  20534.70  23.685315

                        T2M_min  T2M_max  T2M_sum  T2MWET_mean  T2MWET_min  \
YEAR      DISTRICT
1982/1983 Achham           6.69    30.43  6970.98    12.374877       -0.99
          Arghakhanchi    10.99    34.07  8204.52     8.292548      -11.68
          Baglung          1.57    22.69  4852.60     2.833507      -14.29
          Baitadi         -3.38    19.62  3349.98    -0.891918      -16.10
          Bajhang         -8.38    15.52  1697.07    -3.767753      -19.07
...                         ...      ...      ...          ...         ...
2018/2019 Syangja          6.85    26.06  6428.46     9.306055       -6.36
          Tanahu          -0.74    19.83  4329.92     5.320630      -11.97
          Taplejung        2.46    21.42  5018.29     7.436274       -8.89
          Tehrathum        2.46    21.42  5018.29     7.436274       -8.89
          Udayapur        12.44    33.43  8645.14    13.602301       -1.57

                        T2MWET_max  T2MWET_sum  T2M_MAX_mean  T2M_MAX_min  \
YEAR      DISTRICT
1982/1983 Achham             23.87     4516.83     25.967479        10.44
          Arghakhanchi       23.42     3026.78     28.893479        17.03
          Baglung            17.20     1034.23     19.143616         7.44
          Baitadi            14.52     -325.55     15.637370         1.92
          Bajhang            11.23    -1375.23     11.253288        -3.40
...                            ...         ...           ...          ...
2018/2019 Syangja            21.12     3396.71     23.026055        11.54
          Tanahu             16.89     1942.03     16.867918         4.05
          Taplejung          17.78     2714.24     18.993726         8.43
          Tehrathum          17.78     2714.24     18.993726         8.43
          Udayapur           24.87     4964.84     29.383808        17.94

                        T2M_MAX_max  T2M_MAX_sum  T2M_MIN_mean  T2M_MIN_min  \
YEAR      DISTRICT
1982/1983 Achham              38.94      9478.13     13.345041         0.30
          Arghakhanchi        42.98     10546.12     17.407589         5.51
          Baglung             31.21      6987.42      8.798411        -2.64
          Baitadi             26.39      5707.64      4.054356        -9.57
          Bajhang             21.84      4107.45     -0.529178       -14.76
...                             ...          ...           ...          ...
2018/2019 Syangja             32.86      8404.51     13.293233         0.48
          Tanahu              24.51      6156.79      7.775452       -10.50
          Taplejung           26.63      6932.71      9.745589        -4.22
          Tehrathum           26.63      6932.71      9.745589        -4.22
          Udayapur            39.50     10725.09     19.167315         7.38

                        T2M_MIN_max  T2M_MIN_sum  T2M_RANGE_mean  \
YEAR      DISTRICT
1982/1983 Achham              23.97      4870.94       12.622438
          Arghakhanchi        27.56      6353.77       11.485699
          Baglung             18.07      3211.42       10.345507
          Baitadi             14.69      1479.84       11.583096
          Bajhang             10.99      -193.15       11.782438
...                             ...          ...             ...
2018/2019 Syangja             22.10      4852.03        9.732877
          Tanahu              16.65      2838.04        9.092466
          Taplejung           17.84      3557.14        9.248055
          Tehrathum           17.84      3557.14        9.248055
          Udayapur            28.36      6996.07       10.216548

                        T2M_RANGE_min  T2M_RANGE_max  T2M_RANGE_sum  \
YEAR      DISTRICT
1982/1983 Achham                 3.61          21.34        4607.19
          Arghakhanchi           3.78          18.79        4192.28
          Baglung                3.77          18.06        3776.11
          Baitadi                4.71          19.67        4227.83
          Bajhang                5.21          20.57        4300.59
...                               ...            ...            ...
2018/2019 Syangja                2.92          16.77        3552.50
          Tanahu                 3.11          18.88        3318.75
          Taplejung              3.08          16.64        3375.54
          Tehrathum              3.08          16.64        3375.54
          Udayapur               3.02          17.81        3729.04

                          TS_mean  TS_min  TS_max   TS_sum  WS10M_mean  \
YEAR      DISTRICT
1982/1983 Achham        18.361644    4.73   31.34  6702.00    2.249288
          Arghakhanchi  22.155562    9.05   35.11  8086.78    2.677178
          Baglung       12.878822    0.24   24.41  4700.77    2.222658
          Baitadi        9.069890   -4.97   22.15  3310.51    2.310849
          Bajhang        4.983726   -9.61   18.21  1819.06    2.536274
...                           ...     ...     ...      ...         ...
2018/2019 Syangja       16.915151    4.50   27.04  6174.03    2.160740
          Tanahu        11.225616   -3.86   20.59  4097.35    2.063068
          Taplejung     13.408384    0.09   22.93  4894.06    2.129644
          Tehrathum     13.408384    0.09   22.93  4894.06    2.129644
          Udayapur      23.455123   10.38   34.55  8561.12    2.515425

                        WS10M_min  WS10M_max  WS10M_sum  WS10M_MAX_mean  \
YEAR      DISTRICT
1982/1983 Achham             1.36       4.18     820.99        4.393726
          Arghakhanchi       1.16       6.52     977.17        4.695863
          Baglung            1.15       3.83     811.27        4.849507
          Baitadi            1.11       5.58     843.46        5.084301
          Bajhang            1.21       7.41     925.74        5.789041
...                           ...        ...        ...             ...
2018/2019 Syangja            1.38       4.54     788.67        4.079753
          Tanahu             1.11       4.41     753.02        4.260274
          Taplejung          0.93       4.93     777.32        4.611151
          Tehrathum          0.93       4.93     777.32        4.611151
          Udayapur           1.05       5.80     918.13        4.312219

                        WS10M_MAX_min  WS10M_MAX_max  WS10M_MAX_sum  \
YEAR      DISTRICT
1982/1983 Achham                 2.33           8.62        1603.71
          Arghakhanchi           1.76          12.55        1713.99
          Baglung                2.18           9.11        1770.07
          Baitadi                2.32          12.10        1855.77
          Bajhang                2.54          14.28        2113.00
...                               ...            ...            ...
2018/2019 Syangja                2.48           7.70        1489.11
          Tanahu                 2.29           8.45        1555.00
          Taplejung              2.59           7.46        1683.07
          Tehrathum              2.59           7.46        1683.07
          Udayapur               1.64          11.59        1573.96

                        WS10M_MIN_mean  WS10M_MIN_min  WS10M_MIN_max  \
YEAR      DISTRICT
1982/1983 Achham              0.452164           0.03           1.90
          Arghakhanchi        1.026274           0.07           3.87
          Baglung             0.400932           0.01           1.34
          Baitadi             0.372521           0.02           2.16
          Bajhang             0.458411           0.04           2.78
...                                ...            ...            ...
2018/2019 Syangja             0.611589           0.07           3.00
          Tanahu              0.351096           0.01           2.18
          Taplejung           0.388466           0.03           2.65
          Tehrathum           0.388466           0.03           2.65
          Udayapur            0.997123           0.02           3.37

                        WS10M_MIN_sum  WS10M_RANGE_mean  WS10M_RANGE_min  \
YEAR      DISTRICT
1982/1983 Achham               165.04          3.941589             1.71
          Arghakhanchi         374.59          3.669397             0.81
          Baglung              146.34          4.448164             1.80
          Baitadi              135.97          4.711370             2.16
          Bajhang              167.32          5.330603             1.99
...                               ...               ...              ...
2018/2019 Syangja              223.23          3.467918             1.98
          Tanahu               128.15          3.909534             2.06
          Taplejung            141.79          4.222740             2.16
          Tehrathum            141.79          4.222740             2.16
          Udayapur             363.95          3.315178             0.70

                        WS10M_RANGE_max  WS10M_RANGE_sum  WS50M_mean  \
YEAR      DISTRICT
1982/1983 Achham                   7.48          1438.68    2.645753
          Arghakhanchi            10.00          1339.33    3.636767
          Baglung                  7.98          1623.58    2.236959
          Baitadi                 11.63          1719.65    2.273534
          Bajhang                 11.50          1945.67    2.493205
...                                 ...              ...         ...
2018/2019 Syangja                  6.52          1265.79    2.591151
          Tanahu                   7.41          1426.98    2.014000
          Taplejung                6.86          1541.30    2.209945
          Tehrathum                6.86          1541.30    2.209945
          Udayapur                 9.47          1210.04    3.369534

                        WS50M_min  WS50M_max  WS50M_sum  WS50M_MAX_mean  \
YEAR      DISTRICT
1982/1983 Achham             1.57       5.46     965.70        4.543562
          Arghakhanchi       1.42       9.01    1327.42        5.479644
          Baglung            1.18       4.47     816.49        4.241425
          Baitadi            1.09       6.29     829.84        4.490548
          Bajhang            1.26       8.18     910.02        5.191918
...                           ...        ...        ...             ...
2018/2019 Syangja            1.55       5.87     945.77        4.280301
          Tanahu             1.02       4.81     735.11        3.590274
          Taplejung          0.96       5.72     806.63        4.192712
          Tehrathum          0.96       5.72     806.63        4.192712
          Udayapur           1.33       8.00    1229.88        5.010685

                        WS50M_MAX_min  WS50M_MAX_max  WS50M_MAX_sum  \
YEAR      DISTRICT
1982/1983 Achham                 2.59          10.53        1658.40
          Arghakhanchi           2.22          15.33        2000.07
          Baglung                1.84           9.83        1548.12
          Baitadi                1.98          13.22        1639.05
          Bajhang                2.47          15.49        1895.05
...                               ...            ...            ...
2018/2019 Syangja                2.62           8.96        1562.31
          Tanahu                 1.52           8.70        1310.45
          Taplejung              2.21           7.92        1530.34
          Tehrathum              2.21           7.92        1530.34
          Udayapur               2.40          13.77        1828.90

                        WS50M_MIN_mean  WS50M_MIN_min  WS50M_MIN_max  \
YEAR      DISTRICT
1982/1983 Achham              0.574247           0.05           2.73
          Arghakhanchi        1.399452           0.05           6.48
          Baglung             0.515123           0.03           2.18
          Baitadi             0.465808           0.02           2.63
          Bajhang             0.567151           0.03           3.42
...                                ...            ...            ...
2018/2019 Syangja             0.831425           0.12           4.26
          Tanahu              0.446822           0.00           2.76
          Taplejung           0.540110           0.01           3.81
          Tehrathum           0.540110           0.01           3.81
          Udayapur            1.510685           0.08           4.87

                        WS50M_MIN_sum  WS50M_RANGE_mean  WS50M_RANGE_min  \
YEAR      DISTRICT
1982/1983 Achham               209.60          3.969288             1.41
          Arghakhanchi         510.80          4.080000             1.12
          Baglung              188.02          3.725589             1.47
          Baitadi              170.02          4.024904             1.63
          Bajhang              207.01          4.624740             1.99
...                               ...               ...              ...
2018/2019 Syangja              303.47          3.448986             1.64
          Tanahu               163.09          3.143233             1.29
          Taplejung            197.14          3.652548             1.38
          Tehrathum            197.14          3.652548             1.38
          Udayapur             551.40          3.499671             1.05

                        WS50M_RANGE_max  WS50M_RANGE_sum
YEAR      DISTRICT
1982/1983 Achham                   8.92          1448.79
          Arghakhanchi            11.17          1489.20
          Baglung                  8.36          1359.84
          Baitadi                 12.51          1469.09
          Bajhang                 12.07          1688.03
...                                 ...              ...
2018/2019 Syangja                  7.04          1258.88
          Tanahu                   7.08          1147.28
          Taplejung                7.21          1333.18
          Tehrathum                7.21          1333.18
          Udayapur                10.94          1277.38

[2775 rows x 80 columns]

Let's drop all the columns we don't need.

In [16]:
climate_df.drop(columns=['PRECTOT_min', 'PRECTOT_max', 'PRECTOT_mean',
                         'PS_min', 'PS_max', 'PS_sum',
                         'QV2M_min', 'QV2M_max', 'QV2M_sum',
                         'RH2M_min', 'RH2M_max', 'RH2M_sum',
                         'T2M_min', 'T2M_max', 'T2M_sum',
                         'T2MWET_min', 'T2MWET_max', 'T2MWET_sum',
                         'T2M_MAX_max', 'T2M_MAX_min', 'T2M_MAX_sum',
                         'T2M_MIN_min', 'T2M_MIN_max', 'T2M_MIN_sum',
                         'T2M_RANGE_mean', 'T2M_RANGE_min', 'T2M_RANGE_max', 'T2M_RANGE_sum',
                         'TS_min', 'TS_max', 'TS_sum',
                         'WS10M_min', 'WS10M_max', 'WS10M_sum',
                         'WS10M_MAX_max', 'WS10M_MAX_min', 'WS10M_MAX_sum',
                         'WS10M_MIN_min', 'WS10M_MIN_max', 'WS10M_MIN_sum',
                         'WS10M_RANGE_mean', 'WS10M_RANGE_min', 'WS10M_RANGE_max', 'WS10M_RANGE_sum',
                         'WS50M_min', 'WS50M_max', 'WS50M_sum',
                         'WS50M_MAX_max', 'WS50M_MAX_min', 'WS50M_MAX_sum',
                         'WS50M_MIN_min', 'WS50M_MIN_max', 'WS50M_MIN_sum',
                         'WS50M_RANGE_mean', 'WS50M_RANGE_min', 'WS50M_RANGE_max', 'WS50M_RANGE_sum',
                         'LAT_min', 'LAT_max', 'LON_min', 'LON_max', 'LAT_sum', 'LON_sum'],
                inplace=True)
climate_df

                        LAT_mean  LON_mean  PRECTOT_sum    PS_mean  QV2M_mean  \
YEAR      DISTRICT
1982/1983 Achham           29.11      81.3       665.15  87.577863   7.857616
          Arghakhanchi     27.90      83.2       810.13  93.133123   8.912356
          Baglung          28.30      83.6       701.53  79.262877   7.262740
          Baitadi          29.50      80.5       498.34  73.814658   5.931178
          Bajhang          29.60      81.2       413.81  67.878877   5.163945
...                          ...       ...          ...        ...        ...
2018/2019 Syangja          28.00      83.8      1594.53  86.005945   9.939973
          Tanahu           28.00      84.1      1529.04  77.660274   8.610411
          Taplejung        27.40      87.7      1373.49  80.040219   9.461699
          Tehrathum        27.10      87.5      1373.49  80.040219   9.461699
          Udayapur         26.90      86.5      1239.51  95.006329  11.662301

                        RH2M_mean   T2M_mean  T2MWET_mean  T2M_MAX_mean  \
YEAR      DISTRICT
1982/1983 Achham        47.294082  19.098575    12.374877     25.967479
          Arghakhanchi  45.122137  22.478137     8.292548     28.893479
          Baglung       53.903781  13.294795     2.833507     19.143616
          Baitadi       52.656329   9.178027    -0.891918     15.637370
          Bajhang       56.509452   4.649507    -3.767753     11.253288
...                           ...        ...          ...           ...
2018/2019 Syangja       62.634192  17.612219     9.306055     23.026055
          Tanahu        69.434959  11.862795     5.320630     16.867918
          Taplejung     70.148384  13.748740     7.436274     18.993726
          Tehrathum     70.148384  13.748740     7.436274     18.993726
          Udayapur      56.259452  23.685315    13.602301     29.383808

                        T2M_MIN_mean    TS_mean  WS10M_mean  WS10M_MAX_mean  \
YEAR      DISTRICT
1982/1983 Achham           13.345041  18.361644    2.249288        4.393726
          Arghakhanchi     17.407589  22.155562    2.677178        4.695863
          Baglung           8.798411  12.878822    2.222658        4.849507
          Baitadi           4.054356   9.069890    2.310849        5.084301
          Bajhang          -0.529178   4.983726    2.536274        5.789041
...                              ...        ...         ...             ...
2018/2019 Syangja          13.293233  16.915151    2.160740        4.079753
          Tanahu            7.775452  11.225616    2.063068        4.260274
          Taplejung         9.745589  13.408384    2.129644        4.611151
          Tehrathum         9.745589  13.408384    2.129644        4.611151
          Udayapur         19.167315  23.455123    2.515425        4.312219

                        WS10M_MIN_mean  WS50M_mean  WS50M_MAX_mean  \
YEAR      DISTRICT
1982/1983 Achham              0.452164    2.645753        4.543562
          Arghakhanchi        1.026274    3.636767        5.479644
          Baglung             0.400932    2.236959        4.241425
          Baitadi             0.372521    2.273534        4.490548
          Bajhang             0.458411    2.493205        5.191918
...                                ...         ...             ...
2018/2019 Syangja             0.611589    2.591151        4.280301
          Tanahu              0.351096    2.014000        3.590274
          Taplejung           0.388466    2.209945        4.192712
          Tehrathum           0.388466    2.209945        4.192712
          Udayapur            0.997123    3.369534        5.010685

                        WS50M_MIN_mean
YEAR      DISTRICT
1982/1983 Achham              0.574247
          Arghakhanchi        1.399452
          Baglung             0.515123
          Baitadi             0.465808
          Bajhang             0.567151
...                                ...
2018/2019 Syangja             0.831425
          Tanahu              0.446822
          Taplejung           0.540110
          Tehrathum           0.540110
          Udayapur            1.510685

[2775 rows x 17 columns]

In [17]:
climate_df.rename(columns = {'PRECTOT_sum':'PRECTOT',
                             'PS_mean':'PS',
                             'QV2M_mean':'QV2M',
                             'RH2M_mean':'RH2M',
                             'T2M_mean':'T2M',
                             'T2MWET_mean':'T2MWET',
                             'T2M_MAX_mean':'T2M_MAX',
                             'T2M_MIN_mean':'T2M_MIN',
                             'TS_mean':'TS',
                             'WS10M_mean':'WS10M',
                             'WS10M_MAX_mean':'WS10M_MAX',
                             'WS10M_MIN_mean':'WS10M_MIN',
                             'WS50M_mean':'WS50M',
                             'WS50M_MAX_mean':'WS50M_MAX',
                             'WS50M_MIN_mean':'WS50M_MIN',
                             'LAT_mean':'LAT',
                             'LON_mean':'LON'},
                  inplace=True)

#Readd the T2M_RANGE, WS10M_RANGE and WS50M_RANGE columns
climate_df['T2M_RANGE'] = climate_df['T2M_MAX'] - climate_df['T2M_MIN']
climate_df['WS10M_RANGE'] = climate_df['WS10M_MAX'] - climate_df['WS10M_MIN']
climate_df['WS50M_RANGE'] = climate_df['WS50M_MAX'] - climate_df['WS50M_MIN']

#Rename 'YEAR' and 'DISTRICT' to 'Year' and 'District'
climate_df.reset_index(names=['YEAR', 'DISTRICT'], inplace=True)
climate_df.rename(columns={
    'YEAR':'Year',
    'DISTRICT':'District'
}, inplace=True)
climate_df.set_index(['Year', 'District'], inplace=True)

climate_df

                          LAT   LON  PRECTOT         PS       QV2M       RH2M  \
Year      District
1982/1983 Achham        29.11  81.3   665.15  87.577863   7.857616  47.294082
          Arghakhanchi  27.90  83.2   810.13  93.133123   8.912356  45.122137
          Baglung       28.30  83.6   701.53  79.262877   7.262740  53.903781
          Baitadi       29.50  80.5   498.34  73.814658   5.931178  52.656329
          Bajhang       29.60  81.2   413.81  67.878877   5.163945  56.509452
...                       ...   ...      ...        ...        ...        ...
2018/2019 Syangja       28.00  83.8  1594.53  86.005945   9.939973  62.634192
          Tanahu        28.00  84.1  1529.04  77.660274   8.610411  69.434959
          Taplejung     27.40  87.7  1373.49  80.040219   9.461699  70.148384
          Tehrathum     27.10  87.5  1373.49  80.040219   9.461699  70.148384
          Udayapur      26.90  86.5  1239.51  95.006329  11.662301  56.259452

                              T2M     T2MWET    T2M_MAX    T2M_MIN         TS  \
Year      District
1982/1983 Achham        19.098575  12.374877  25.967479  13.345041  18.361644
          Arghakhanchi  22.478137   8.292548  28.893479  17.407589  22.155562
          Baglung       13.294795   2.833507  19.143616   8.798411  12.878822
          Baitadi        9.178027  -0.891918  15.637370   4.054356   9.069890
          Bajhang        4.649507  -3.767753  11.253288  -0.529178   4.983726
...                           ...        ...        ...        ...        ...
2018/2019 Syangja       17.612219   9.306055  23.026055  13.293233  16.915151
          Tanahu        11.862795   5.320630  16.867918   7.775452  11.225616
          Taplejung     13.748740   7.436274  18.993726   9.745589  13.408384
          Tehrathum     13.748740   7.436274  18.993726   9.745589  13.408384
          Udayapur      23.685315  13.602301  29.383808  19.167315  23.455123

                           WS10M  WS10M_MAX  WS10M_MIN     WS50M  WS50M_MAX  \
Year      District
1982/1983 Achham        2.249288   4.393726   0.452164  2.645753   4.543562
          Arghakhanchi  2.677178   4.695863   1.026274  3.636767   5.479644
          Baglung       2.222658   4.849507   0.400932  2.236959   4.241425
          Baitadi       2.310849   5.084301   0.372521  2.273534   4.490548
          Bajhang       2.536274   5.789041   0.458411  2.493205   5.191918
...                          ...        ...        ...       ...        ...
2018/2019 Syangja       2.160740   4.079753   0.611589  2.591151   4.280301
          Tanahu        2.063068   4.260274   0.351096  2.014000   3.590274
          Taplejung     2.129644   4.611151   0.388466  2.209945   4.192712
          Tehrathum     2.129644   4.611151   0.388466  2.209945   4.192712
          Udayapur      2.515425   4.312219   0.997123  3.369534   5.010685

                        WS50M_MIN  T2M_RANGE  WS10M_RANGE  WS50M_RANGE
Year      District
1982/1983 Achham         0.574247  12.622438     3.941562     3.969315
          Arghakhanchi   1.399452  11.485890     3.669589     4.080192
          Baglung        0.515123  10.345205     4.448575     3.726301
          Baitadi        0.465808  11.583014     4.711781     4.024740
          Bajhang        0.567151  11.782466     5.330630     4.624767
...                           ...        ...          ...          ...
2018/2019 Syangja        0.831425   9.732822     3.468164     3.448877
          Tanahu         0.446822   9.092466     3.909178     3.143452
          Taplejung      0.540110   9.248137     4.222685     3.652603
          Tehrathum      0.540110   9.248137     4.222685     3.652603
          Udayapur       1.510685  10.216493     3.315096     3.500000

[2775 rows x 20 columns]

## Modifying crop dataset

In [18]:
crop_df #view the crop dataset

,DISTRICT_CODE,DISTRICT_NAME,PD_P_197980,PD_P_198081,PD_P_198182,PD_P_198283,PD_P_198384,PD_P_198485,PD_P_198586,PD_P_198687,PD_P_198788,PD_P_198889,PD_P_199091,PD_P_199192,PD_P_199293,PD_P_199394,PD_P_199495,PD_P_199596,PD_P_199697,PD_P_199798,PD_P_199899,PD_P_199900,PD_P_200001,PD_P_200102,PD_P_200203,PD_P_200304,PD_P_200405,PD_P_200506,PD_P_200607,PD_P_200708,PD_P_200809,PD_P_200910,PD_P_201011,PD_P_201112,PD_P_201213,PD_P_201314,MZ_P_197980,MZ_P_198081,MZ_P_198182,MZ_P_198283,MZ_P_198384,MZ_P_198485,MZ_P_198586,MZ_P_198687,MZ_P_198788,MZ_P_198889,MZ_P_199091,MZ_P_199192,MZ_P_199293,MZ_P_199394,MZ_P_199495,MZ_P_199596,MZ_P_199697,MZ_P_199798,MZ_P_199899,MZ_P_199900,MZ_P_200001,MZ_P_200102,MZ_P_200203,MZ_P_200304,MZ_P_200405,MZ_P_200506,MZ_P_200607,MZ_P_200708,MZ_P_200809,MZ_P_200910,MZ_P_201011,MZ_P_201112,MZ_P_201213,MZ_P_201314,ML_P_197980,ML_P_198081,ML_P_198182,ML_P_198283,ML_P_198384,ML_P_198485,ML_P_198586,ML_P_198687,ML_P_198788,ML_P_198889,ML_P_199091,ML_P_199192,ML_P_199293,ML_P_199394,ML_P_199495,ML_P_199596,ML_P_199697,ML_P_199798,ML_P_199899,ML_P_199900,ML_P_200001,ML_P_200102,ML_P_200203,ML_P_200304,ML_P_200405,ML_P_200506,ML_P_200607,ML_P_200708,ML_P_200809,ML_P_200910,ML_P_201011,ML_P_201112,ML_P_201213,ML_P_201314,WT_P_197980,WT_P_198081,WT_P_198182,WT_P_198283,WT_P_198384,WT_P_198485,WT_P_198586,WT_P_198687,WT_P_198788,WT_P_198889,WT_P_199091,WT_P_199192,WT_P_199293,WT_P_199394,WT_P_199495,WT_P_199596,WT_P_199697,WT_P_199798,WT_P_199899,WT_P_199900,WT_P_200001,WT_P_200102,WT_P_200203,WT_P_200304,WT_P_200405,WT_P_200506,WT_P_200607,WT_P_200708,WT_P_200809,WT_P_200910,WT_P_201011,WT_P_201112,WT_P_201213,WT_P_201314,BL_P_197980,BL_P_198081,BL_P_198182,BL_P_198283,BL_P_198384,BL_P_198485,BL_P_198586,BL_P_198687,BL_P_198788,BL_P_198889,BL_P_199091,BL_P_199192,BL_P_199293,BL_P_199394,BL_P_199495,BL_P_199596,BL_P_199697,BL_P_199798,BL_P_199899,BL_P_199900,BL_P_200001,BL_P_200102,BL_P_200203,BL_P_200304,BL_P_200405,BL_P_200506,BL_P_200607,BL_P_200708,BL_P_200809,BL_P_200910,BL_P_201011,BL_P_201112,BL_P_201213,BL_P_201314,PD_A_197980,PD_A_198081,PD_A_198182,PD_A_198283,PD_A_198384,PD_A_198485,PD_A_198586,PD_A_198687,PD_A_198788,PD_A_198889,PD_A_199091,PD_A_199192,PD_A_199293,PD_A_199394,PD_A_199495,PD_A_199596,PD_A_199697,PD_A_199798,PD_A_199899,PD_A_199900,PD_A_200001,PD_A_200102,PD_A_200203,PD_A_200304,PD_A_200405,PD_A_200506,PD_A_200607,PD_A_200708,PD_A_200809,PD_A_200910,PD_A_201011,PD_A_201112,PD_A_201213,PD_A_201314,MZ_A_197980,MZ_A_198081,MZ_A_198182,MZ_A_198283,MZ_A_198384,MZ_A_198485,MZ_A_198586,MZ_A_198687,MZ_A_198788,MZ_A_198889,MZ_A_199091,MZ_A_199192,MZ_A_199293,MZ_A_199394,MZ_A_199495,MZ_A_199596,MZ_A_199697,MZ_A_199798,MZ_A_199899,MZ_A_199900,MZ_A_200001,MZ_A_200102,MZ_A_200203,MZ_A_200304,MZ_A_200405,MZ_A_200506,MZ_A_200607,MZ_A_200708,MZ_A_200809,MZ_A_200910,MZ_A_201011,MZ_A_201112,MZ_A_201213,MZ_A_201314,ML_A_197980,ML_A_198081,ML_A_198182,ML_A_198283,ML_A_198384,ML_A_198485,ML_A_198586,ML_A_198687,ML_A_198788,ML_A_198889,ML_A_199091,ML_A_199192,ML_A_199293,ML_A_199394,ML_A_199495,ML_A_199596,ML_A_199697,ML_A_199798,ML_A_199899,ML_A_199900,ML_A_200001,ML_A_200102,ML_A_200203,ML_A_200304,ML_A_200405,ML_A_200506,ML_A_200607,ML_A_200708,ML_A_200809,ML_A_200910,ML_A_201011,ML_A_201112,ML_A_201213,ML_A_201314,WT_A_197980,WT_A_198081,WT_A_198182,WT_A_198283,WT_A_198384,WT_A_198485,WT_A_198586,WT_A_198687,WT_A_198788,WT_A_198889,WT_A_199091,WT_A_199192,WT_A_199293,WT_A_199394,WT_A_199495,WT_A_199596,WT_A_199697,WT_A_199798,WT_A_199899,WT_A_199900,WT_A_200001,WT_A_200102,WT_A_200203,WT_A_200304,WT_A_200405,WT_A_200506,WT_A_200607,WT_A_200708,WT_A_200809,WT_A_200910,WT_A_201011,WT_A_201112,WT_A_201213,WT_A_201314,BL_A_197980,BL_A_198081,BL_A_198182,BL_A_198283,BL_A_198384,BL_A_198485,BL_A_198586,BL_A_198687,BL_A_198788,BL_A_198889,BL_A_199091,BL_A_199192,BL_A_199293,BL_A_199394,BL_A_199495,BL_A_199596,BL_A_199697,BL_A_199798,BL_A_199899,BL_A_199900,BL_A_200001,BL_A_200102,BL_A_200203,BL_A_200304,BL_A_200405,BL_A_200506,BL_A_200607,BL_A_200708,BL_A_200809,BL_A_200910,BL_A_201011,BL_A_201112,BL_A_201213,BL_A_201314,PD_Y_197980,PD_Y_198081,PD_Y_198182,PD_Y_198283,PD_Y_198384,PD_Y_198485,PD_Y_198586,PD_Y_198687,PD_Y_198788,PD_Y_198889,PD_Y_199091,PD_Y_199192,PD_Y_199293,PD_Y_199394,PD_Y_199495,PD_Y_199596,PD_Y_199697,PD_Y_199798,PD_Y_199899,PD_Y_199900,PD_Y_200001,PD_Y_200102,PD_Y_200203,PD_Y_200304,PD_Y_200405,PD_Y_200506,PD_Y_200607,PD_Y_200708,PD_Y_200809,PD_Y_200910,PD_Y_201011,PD_Y_201112,PD_Y_201213,PD_Y_201314,MZ_Y_197980,MZ_Y_198081,MZ_Y_198182,MZ_Y_198283,MZ_Y_198384,MZ_Y_198485,MZ_Y_198586,MZ_Y_198687,MZ_Y_198788,MZ_Y_198889,MZ_Y_199091,MZ_Y_199192,MZ_Y_199293,MZ_Y_199394,MZ_Y_199495,MZ_Y_199596,MZ_Y_199697,MZ_Y_199798,MZ_Y_199899,MZ_Y_199900,MZ_Y_200001,MZ_Y_200102,MZ_Y_200203,MZ_Y_200304,MZ_Y_200405,MZ_Y_200506,MZ_Y_200607,MZ_Y_200708,MZ_Y_200809,MZ_Y_200910,MZ_Y_201011,MZ_Y_201112,MZ_Y_201213,MZ_Y_201314,ML_Y_197980,ML_Y_198081,ML_Y_198182,ML_Y_198283,ML_Y_198384,ML_Y_198485,ML_Y_198586,ML_Y_198687,ML_Y_198788,ML_Y_198889,ML_Y_199091,ML_Y_199192,ML_Y_199293,ML_Y_199394,ML_Y_199495,ML_Y_199596,ML_Y_199697,ML_Y_199798,ML_Y_199899,ML_Y_199900,ML_Y_200001,ML_Y_200102,ML_Y_200203,ML_Y_200304,ML_Y_200405,ML_Y_200506,ML_Y_200607,ML_Y_200708,ML_Y_200809,ML_Y_200910,ML_Y_201011,ML_Y_201112,ML_Y_201213,ML_Y_201314,WT_Y_197980,WT_Y_198081,WT_Y_198182,WT_Y_198283,WT_Y_198384,WT_Y_198485,WT_Y_198586,WT_Y_198687,WT_Y_198788,WT_Y_198889,WT_Y_199091,WT_Y_199192,WT_Y_199293,WT_Y_199394,WT_Y_199495,WT_Y_199596,WT_Y_199697,WT_Y_199798,WT_Y_199899,WT_Y_199900,WT_Y_200001,WT_Y_200102,WT_Y_200203,WT_Y_200304,WT_Y_200405,WT_Y_200506,WT_Y_200607,WT_Y_200708,WT_Y_200809,WT_Y_200910,WT_Y_201011,WT_Y_201112,WT_Y_201213,WT_Y_201314,BL_Y_197980,BL_Y_198081,BL_Y_198182,BL_Y_198283,BL_Y_198384,BL_Y_198485,BL_Y_198586,BL_Y_198687,BL_Y_198788,BL_Y_198889,BL_Y_199091,BL_Y_199192,BL_Y_199293,BL_Y_199394,BL_Y_199495,BL_Y_199596,BL_Y_199697,BL_Y_199798,BL_Y_199899,BL_Y_199900,BL_Y_200001,BL_Y_200102,BL_Y_200203,BL_Y_200304,BL_Y_200405,BL_Y_200506,BL_Y_200607,BL_Y_200708,BL_Y_200809,BL_Y_200910,BL_Y_201011,BL_Y_201112,BL_Y_201213,BL_Y_201314,BW_P_201011,BW_P_201112,BW_P_201213,BW_P_201314,BW_A_201011,BW_A_201112,BW_A_201213,BW_A_201314,BW_Y_201011,BW_Y_201112,BW_Y_201213,BW_Y_201314
0,1,Taplejung,3320,3400,3570,3010,3070,3190,3800,3610,3780,4280,11870,11860,11570,12160,10540,12250,12250,14175,14200,14250,15837,17043.5,18250,18250.0,19737.675,19089.0,16048.0,16048.0,16048.0,15600,20099.700,22167.0,10913,13861,7920,9630,10640,10430,10110,9920,7840,7940,7170,6860,12410,12510,12620,14000,12974,13440,14000,15110,14280,17363,19312,20636,21960,21960,22170.900,22881.25,24018.775,28495.0,28495.0,26300,36795.000,38116.0,27450,49408,1700,1660,1660,2270,2420,1900,2000,2000,1920,2780,2520,2530,2750,4100,4250,5000,5010,6350,6350,6350,4214,6350,3100,3720,3565.0,3660.0,3500.0,3567.0,3567.0,3050,3813.0,3508.0,3507,4418,290,730,1210,570,520,980,1750,1760,1610,1930,2130,2180,2160,2925,2985,2430,2344,2695,1752,2774,3288.0,3288,3206,3492.0,3832.0,2879.0,2879.0,2879.0,2285,1890,3921.0,2783,3600,2016,160,110,120,50,60,100,120,130,140,160,190,200,250,554,606,424,425,186,259,325,288,288,290,336,288,288,288.0,288.0,264,264,300.0,280.0,312,300,1880,1900,1900,1600,1600,1740,2000,2260,2300,2350,6480,6480,6430,6499,6200,6500,6500,7000,7000,7510,8220,4927,8990,8990,9025,9090,8783,8783,8783,8710,9710,10477,4850,6950,5310,5600,5600,5600,5600,6200,5600,5670,5690,5580,9220,9320,9350,10000,9300,9600,10000,10210,10200,12463,12500,12463,13150,13150,13150,13075,13075,13187,13187,13200,16075,16075,9150,16075,1400,1380,1380,2020,2020,1730,2000,2020,2130,2700,2400,2410,2500,4100,4100,4990,5000,5631,5631,5631,3512,5631,3100,3100,3100,3050,3050,3050,3050,3050,3050,3050,3050,3290,260,650,1100,520,520,750,1750,1760,1790,1780,1820,1800,1950,1990,1620,1830,1925,1895,1750,1895,1895,189,1810,1895,1895,1895,1895,1895,1890,1890,1895,1210,1895,925,260,130,130,60,60,120,150,180,190,220,230,250,550,600,386,387,209,216,200,250,240,240,240,240,240,240,240,240,240,240,240,240,240,200,1766,1789,1879,1881,1919,1833,1900,1597,1643,1821,1832,1830,1799,1871,1700,1885,1885,2025,2029,1897,1927,3459,2030,2030,2187,2100,1827,1827,1827,1791,2070,2116,2250,1994,1492,1720,1900,1863,1805,1600,1400,1400,1260,1229,1346,1342,1350,1400,1395,1400,1400,1480,1400,1393,1545,1656,1670,1670,1686,1750,1837,2161,2161,1992,2289,2371,3000,3074,1214,1203,1203,1124,1198,1098,1000,990,901,1030,1050,1050,1100,1000,1037,1002,1002,1128,1128,1128,1200,1128,1000,1200,1150,1200,1148,1170,1170,1000,1250,1150,1150,1343,1115,1123,1100,1096,1000,1307,1000,1000,899,1084,1170,1211,1108,1470,1843,1328,1218,1422,1001,1464,1735,17397,1771,1843,2022,1519,1519,1519,1209,1000,2069,2300,1900,2179,615,846,923,833,1000,833,800,722,737,727,826,800,455,923,1570,1096,2033,861,1295,1300,1200,1200,1208,1400,1200,1200,1200,1200,1100,1100,1250,1167,1300,1500,0.0,170.0,165,170,0,155.0,118,120,0.00,1096.77,1398,1416.67
1,2,Panchthar,7180,7000,5680,3810,14350,17440,18390,17600,20360,20730,19530,18750,18030,16659,12171,18270,19160,19015,19712,21426,23150,22580.0,22010,22010.0,20776.000,20776.0,15800.0,15800.0,15879.0,15000,21840.000,23000.0,22600,30127,12150,12120,13740,9640,13210,24000,25530,22500,22100,24640,22130,22230,22880,24000,24345,25239,25100,28050,27225,26155,27118,26155,16681,16681,21231.000,21231.00,21231.000,22089.0,22133.0,21225,21232.500,21760.0,12240,29931,3160,3250,3250,3060,3230,4570,4060,5260,5060,5150,6600,6600,6500,6060,6060,6011,6100,6976,7560,7421,9703,7421,5975,7170,8564.0,7965.0,7700.0,7790.0,7750.0,7150,8350.0,9350.0,9350,9046,980,960,1130,1280,1230,3920,4150,4390,3980,4000,4020,4100,4200,5926,6981,6896,7619,7650,7268,7520,7520.0,4970,5720,5900.0,7380.0,7000.0,7410.0,7410.0,6300,4130,7400.0,7580,7632,6732,150,40,40,150,240,410,400,430,440,400,430,410,480,292,320,470,467,467,494,468,468,455,553,638,744,570,674.0,674.0,515,515,600.0,593.0,552,500,3990,3550,3550,2050,8970,10170,10220,10320,11700,11710,9690,9730,9750,9800,7380,10150,10360,10334,10375,10413,10409,6730,10480,10480,10388,10388,8854,8854,8854,8400,10400,11500,11300,10322,9000,8080,8080,7510,7610,14110,14100,14060,14250,16000,15170,15200,15250,15000,15350,16315,16300,16500,16500,14138,14250,14138,14151,14151,14154,14154,14154,14160,14160,14150,14155,12800,8000,18627,3620,3610,3610,3400,3400,4810,5810,5850,6000,6100,6200,6210,6250,6000,6000,5952,6000,5952,5952,5955,5953,5955,5975,5975,5978,5978,5978,5992,5992,4911,5000,5000,5000,4805,820,800,900,1140,1120,3500,3600,3660,3550,3980,4030,4000,3299,4083,4033,4088,4090,4091,3890,4091,4091,4097,4100,4100,4100,4100,4115,4115,4130,4130,4000,4000,3995,3120,180,50,50,300,300,450,500,510,520,510,500,510,320,350,515,519,519,520,500,520,520,535,540,532,532,532,519,519,515,515,500,494,460,450,1799,1972,1600,1859,1600,1715,1799,1705,1740,1770,2015,1927,1849,1700,1649,1800,1849,1840,1900,2058,2224,3355,2100,2100,2000,2000,1785,1785,1793,1786,2100,2000,2000,2919,1350,1500,1700,1284,1736,1701,1811,1600,1551,1540,1459,1463,1500,1600,1586,1547,1540,1700,1650,1850,1903,1850,1179,1179,1500,1500,1500,1560,1563,1500,1500,1700,1530,1607,873,900,900,900,950,950,699,899,843,844,1065,1063,1040,1010,1010,1010,1017,1172,1270,1246,1630,1246,1000,1200,1433,1332,1288,1300,1293,1456,1670,1870,1870,1883,1195,1200,1256,1123,1098,1120,1153,1199,1121,1005,998,1025,1273,1451,1731,1687,1863,1870,1868,1838,1838,1213,1395,1439,1800,1707,1801,1801,1525,1000,1850,1895,1910,2158,833,800,800,500,800,911,800,843,846,784,860,804,1500,834,621,906,900,898,988,900,900,850,1024,1199,1398,1071,1299,1299,1000,1000,1200,1200,1200,1111,42.0,42.0,36,36,60,60.0,56,56,700.00,700.00,643,642.86
2,3,Ilam,18700,27530,30290,15840,20040,27270,24950,21340,18440,21420,23520,23990,21680,20670,20113,24250,24750,26900,26995,30274,27000,20851.0,28800,28800.0,31966.439,35538.0,29500.0,28299.0,36300.0,35914,45690.000,45690.0,45185,44966,8100,14350,16000,11050,15220,22690,27780,26620,22890,20240,26660,26700,29120,40500,39710,40410,40500,41866,41175,48005,44612,43681,44350,44350,46550.000,42415.00,46940.000,57526.0,57526.0,58500,77500.000,77500.0,78385,69654,2840,2730,1600,1480,1750,2610,2160,2410,2650,3020,3560,3550,3280,4843,4238,4206,4500,3402,3402,4030,4030,3290,3213,3373,3290.0,3390.0,3312.0,2884.0,2884.0,3612,3312.0,3000.0,2670,3000,2400,2980,2660,2090,2730,4020,4700,3980,3990,5990,5620,5550,5610,7098,7200,7200,7568,6622,6332,8530,7882.0,8081,8062,8050.0,8945.0,8500.0,9020.0,10627.0,8250,4735,13365.0,13398,12960,12350,50,50,10,10,60,70,90,110,120,120,120,110,130,220,240,240,240,5,5,5,80,71,71,70,72,72,75.0,75.0,75,75,75.0,55.0,50,50,7500,11470,13170,9900,10120,12440,12450,12400,10670,10700,11640,11820,11720,11700,11493,12217,12500,13182,13200,13550,13550,12405,13605,13605,14471,14625,12091,12304,13200,13084,14825,14825,14815,14185,6300,8900,8900,5610,8510,15120,15220,15200,15250,15200,15240,15300,16180,22500,22000,22450,22500,22630,22650,23335,23480,24335,24500,24500,24500,22927,23470,23480,23480,23480,31480,31480,31480,28200,2430,2100,2000,1950,1950,2900,2700,2680,3120,3000,3260,3250,3000,4600,4025,4427,4500,3680,3680,4030,4030,3290,3213,3213,3290,3290,3312,3314,3314,3312,3312,3000,3000,3000,1730,2180,1900,1860,2100,3070,3900,3950,3980,4130,4140,4150,4670,4715,4714,4730,4740,4533,4500,4740,4777,4592,4607,4600,4708,4708,4735,4735,4735,4735,4800,4620,4700,4697,50,70,10,10,60,80,100,120,130,130,120,140,230,250,250,250,9,9,120,9,90,71,71,70,72,72,75,75,75,75,75,55,55,50,2493,2400,2300,1600,1980,2192,2004,1721,1728,2002,2021,2030,1850,1767,1750,1985,1980,2041,2045,2234,1993,1681,2117,2117,2209,2430,2440,2300,2750,2745,3082,3082,3050,3170,1286,1612,1798,1970,1788,1501,1825,1751,1501,1332,1749,1745,1800,1800,1805,1800,1800,1850,1818,2057,1900,1795,1810,1810,1900,1850,2000,2450,2450,2491,2462,2462,2490,2470,1169,1300,800,759,897,900,800,899,849,1007,1092,1092,1093,1053,1053,950,1000,924,924,1000,1000,1000,1000,1050,1000,1030,1000,870,870,1091,1000,1000,890,1000,1387,1367,1400,1124,1300,1309,1205,1008,1003,1450,1357,1337,1201,1505,1527,1522,1597,1461,1407,1800,1650,1760,1750,1750,1900,1805,1905,2244,1742,1000,2784,2900,2757,2629,1000,714,1000,1000,1000,875,900,917,923,923,1000,786,565,880,960,960,26667,556,42,556,889,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,909,1000,20.0,20.0,17,20,28,28.0,25,25,714.29,714.29,680,800.00
3,4,Jhapa,148020,152250,137070,126570,160820,143380,153100,147380,167800,216770,206900,252290,202630,228799,189438,253128,261710,247590,283500,293000,292858,247680.0,290660,298600.0,314843.750,311690.0,243290.0,312523.0,322640.0,264000,271920.000,321840.0,320790,365250,4170,6750,6820,13090,11730,13680,10360,12600,8790,16000,13330,13590,18630,25600,28825,31450,28690,26810,34255,40110,38190,42110,42300,42300,44000.000,47837.50,54250.000,56627.0,58600.0,58600,62310.000,72460.0,82140,95000,820,850,1140,1100,1200,590,710,620,1880,1260,2150,2160,2190,2100,3500,3000,3000,3510,3000,2000,1800,2000,2000,2000,1950.0,2150.0,2340.0,2100.0,2000.0,2160,2160.0,2160.0,1785,1800,6600,6370,6000,12330,12830,5970,5600,10240,15810,14230,13950,13380,13090,11032,18000,24200,22912,25200,21420,30500,28750.0,35650,35650,32280.0,44950.0,39250.0,44200.0,43500.0,36500,14000,24150.0,25150,21750,22540,50,40,40,60,10,10,10,10,20,10,20,20,20,20,30,30,10,10,60,60,60,60,60,11,10,110,22.0,10.0,10,6,7.0,6.0,6,6,87070,87000,91380,84350,90860,92990,86500,85930,85240,86890,88550,88710,80730,87900,78720,93578,94480,94000,94500,95000,91518,84214,92150,92100,96875,96800,81000,96161,96700,80000,82400,89400,86700,88500,2980,4500,4550,9530,6790,8510,7200,7300,7620,10820,10500,10500,13310,16000,16500,18500,19100,19125,20150,20055,20100,21055,21150,21150,22000,22250,21700,22550,22600,22600,24600,24600,36185,36850,990,950,950,900,1200,650,750,690,2350,1260,2000,2000,2010,2100,3500,3000,3000,3510,2800,2000,1800,2000,2000,2000,1950,2150,2200,2100,2000,1800,1800,1800,1785,1750,6000,5100,5000,8220,8020,4390,4000,5690,10200,8250,8110,8500,7500,12000,14250,15275,14000,13275,9180,15000,12700,16500,16511,15100,15500,15700,17000,15000,15000,14000,11500,7500,6500,7000,50,50,50,50,10,10,20,10,20,20,30,20,20,30,30,10,10,50,10,50,50,50,50,11,10,100,11,10,10,8,9,8,8,6,1700,1750,1500,1501,1770,1542,1770,1715,1969,2495,2337,2844,2510,2603,2406,2705,2770,2634,3000,3084,3200,2941,3154,3242,3250,3220,3004,3250,3337,3300,3300,3600,3700,4127,1399,1500,1499,1374,1728,1608,1439,1726,1154,1479,1270,1294,1400,1600,1747,1700,1502,1402,1700,2000,1900,2000,2000,2000,2000,2150,2500,2511,2593,2593,2533,2946,2270,2578,828,895,1200,1222,1000,908,947,899,800,1000,1075,1080,1090,1000,1000,1000,1000,1000,1071,1000,1000,1000,1000,1000,1000,1000,1064,1000,1000,1200,1200,1200,1000,1029,1100,1249,1200,1500,1600,1360,1400,1800,1550,1725,1720,1574,1745,919,1263,1584,1637,1898,2333,2033,2264,2161,2159,2138,2900,2500,2600,2900,2433,1000,2100,3353,3346,3220,1000,800,800,1200,1000,1000,500,1000,1000,500,667,1000,1000,667,1000,3000,1000,200,6000,1200,1200,1200,1200,1000,1000,1100,2000,1000,1000,750,778,750,750,1000,1300.0,1300.0,1265,1270,1300,1300.0,1265,1270,1000.00,1000.00,1000,1000.00
4,5,Sankhuwasabha,20260,18480,18480,14310,15870,21270,22240,20500,23530,29110,28560,26930,25520,17880,17100,18332,19520,18820,19600,21520,22992,18270.0,24267,24267.0,34091.000,28674.0,25030.0,28677.0,28677.0,21732,29816.478,36600.0,23701,35458,5340,12350,12350,12230,12490,19410,17540,17900,15200,14730,15410,15310,15550,13290,14452,15169,14540,16985,16582,21580,20324,21448,21838,21838,22788.804,22623.00,23740.200,28209.0,28209.0,19583,28259.175,22193.5,22226,17000,2550,2000,2000,2000,1800,2630,2600,2330,2680,3000,6810,6800,6900,5800,5850,6409,7500,7500,7500,9104,9100,8090,8160,7349,10093.0,9575.0,9575.0,9956.0,9956.0,10080,9875.0,9975.0,10180,7314,300,460,460,280,1240,1260,1300,1810,2010,2300,2160,2210,2140,2964,2995,2227,2227,2513,1760,3108,3956.0,3956,2470,2164.5,2457.0,2500.0,2850.0,2925.0,2288,1505,2800.0,2850,3000,1915,210,200,220,240,240,250,230,240,240,240,220,230,240,315,362,362,362,284,286,99,99,99,56,80,37,40,48.0,29.0,29,29,26.0,26.0,30,30,8800,8400,8400,8130,8230,11130,11120,11100,11630,13440,11620,11630,11600,9860,9627,10110,10460,10460,10480,10700,11000,10180,11780,11780,15496,15496,15037,15932,15932,13171,15417,15812,15801,13775,5280,7870,7870,7870,8320,9750,9750,9850,9930,9600,9970,9870,9970,8800,9112,9662,9600,10050,10050,12587,11662,12587,12846,12846,12846,13087,13080,14672,14672,13055,14165,13055,13074,12470,2310,2000,2000,2000,2000,2630,2600,2590,2980,3000,6880,6860,6900,5800,5800,6104,7100,7100,7100,9104,9100,8190,8160,8160,9175,9195,9195,9977,9977,9975,9975,9975,9981,7171,260,400,400,270,1130,1150,1200,1500,1520,1590,1610,1650,2151,2170,1591,1595,1675,1775,1530,2275,2275,2275,1235,1170,1170,1350,1500,1500,1505,1505,1400,1450,1450,775,250,240,240,240,240,250,250,250,240,230,250,260,350,400,400,400,376,276,250,76,76,76,70,60,50,40,40,30,30,30,35,35,35,30,2302,2200,2200,1760,1928,1911,2000,1847,2023,2166,2458,2316,2200,1813,1776,1813,1866,1799,1870,2011,2090,1795,2060,2060,2200,1850,1665,1800,1800,1650,1934,2315,1500,2574,1011,1569,1569,1554,1501,1991,1799,1817,1531,1534,1546,1551,1560,1510,1586,1570,1515,1690,1650,1714,1743,1704,1700,1700,1774,1729,1815,1923,1923,1500,1995,1700,1700,1363,1104,1000,1000,1000,900,1000,1000,900,899,1000,990,991,1000,1000,1009,1050,1056,1056,1056,1000,1000,988,1000,901,1100,1041,1041,998,998,1011,990,1000,1020,1020,1154,1150,1150,1037,1097,1096,1083,1207,1322,1447,1342,1339,995,1366,1882,1396,1330,1416,1150,1366,1739,1739,2000,1850,2100,1852,1900,1950,1520,1000,2000,1966,2069,2471,840,833,917,1000,1000,1000,920,960,1000,1043,880,885,686,788,905,905,963,1029,1144,1303,1303,1303,800,1333,740,1000,1200,967,967,967,743,743,857,1000,0.0,11.0,10,15,0,20.0,18,18,0.00,550.00,556,833.33

In [19]:
crop_df.drop(columns=['DISTRICT_CODE'], inplace=True) #drop the 'DISTRICT_CODE' column
crop_df = crop_df.rename(columns={'DISTRICT_NAME': 'Year'}).set_index('Year').T #transpose the dataset
crop_df

Year,Taplejung,Panchthar,Ilam,Jhapa,Sankhuwasabha,Bhojpur,Dhankuta,Tehrathum,Morang,Sunsari,Solukhumbu,Okhaldhunga,Khotang,Udayapur,Saptari,Siraha,Dolakha,Ramechhap,Sindhuli,Dhanusa,Mahottari,Sarlahi,Sindhupalchok,Kavre,Bhaktapur,Lalitpur,Kathmandu,Rasuwa,Nuwakot,Dhading,Rautahat,Bara,Parsa,Makwanpur,Chitwan,Gorkha,Lamjung,Tanahu,Manang,Kaski,Syangja,Nawalparasi,Palpa,Rupandehi,Gulmi,Arghakhanchi,Kapilbastu,Mustang,Myagdi,Parbat,Baglung,Dolpa,Mugu,Jumla,Kalikot,Humla,Rukum,Rolpa,Pyuthan,Dang,Salyan,Jajarkot,Dailekh,Surkhet,Banke,Bardiya,Bajura,Achham,Bajhang,Doti,Kailali,Darchula,Baitadi,Dadeldhura,Kanchanpur
PD_P_197980,3320.00,7180.00,18700.00,148020.0,20260.00,10400.00,16080.0,6960.00,139760.00,91390.0,440.00,4200.00,2420.00,25920.0,144240.0,133490.0,3500.00,7780.0,19530.00,100930.0,113120.0,54840.0,7170.0,16400.0,17360.0,15090.00,37420.0,190.0,16940.0,11790.0,108270.0,106440.0,78270.0,19710.00,45500.00,7560.00,10240.00,18600.00,0.00,23280.00,18620.00,53020.00,7050.00,76150.0,6170.00,3730.00,55320.0,150.00,4300.00,3490.00,3710.0,320.00,350.0,2340.00,380.00,360.0,1280.0,1110.00,6080.00,36930.0,6040.00,5040.00,5320.0,7520.0,26000.0,37930.0,5210.00,2540.0,4590.00,8570.0,32670.0,2380.00,3910.0,1710.0,16930.0
PD_P_198081,3400.00,7000.00,27530.00,152250.0,18480.00,12250.00,18440.0,8000.00,141100.00,91500.0,500.00,4600.00,2500.00,26160.0,145450.0,134250.0,3290.00,9000.0,19680.00,104200.0,122850.0,63650.0,7100.0,16030.0,21450.0,14960.00,35280.0,390.0,17000.0,13490.0,119050.0,108900.0,84610.0,22510.00,48190.00,8550.00,11220.00,17950.00,0.00,23500.00,19000.00,70770.00,11400.00,129660.0,6300.00,4100.00,139610.0,30.00,4000.00,3520.00,5590.0,240.00,560.0,2700.00,430.00,210.0,1640.0,1140.00,7000.00,60080.0,8570.00,5710.00,6120.0,12860.0,52120.0,60200.0,3260.00,3600.0,4510.00,10400.0,86700.0,2190.00,6570.0,3600.0,43660.0
PD_P_198182,3570.00,5680.00,30290.00,137070.0,18480.00,14640.00,19370.0,17750.00,152890.00,107360.0,950.00,4250.00,2380.00,23040.0,104080.0,112220.0,3840.00,7550.0,16540.00,98060.0,126020.0,73850.0,7100.0,18050.0,28700.0,18950.00,52530.0,320.0,24630.0,20820.0,109030.0,140940.0,132000.0,19770.00,62000.00,8790.00,10590.00,28130.00,0.00,41920.00,21850.00,62470.00,15750.00,99370.0,6360.00,3580.00,141250.0,20.00,3780.00,3560.00,7550.0,390.00,560.0,3480.00,430.00,240.0,1640.0,1140.00,7000.00,56680.0,8570.00,5740.00,7530.0,13570.0,56850.0,60130.0,3200.00,3770.0,5180.00,13150.0,73790.0,2300.00,6600.0,3450.0,55000.0
PD_P_198283,3010.00,3810.00,15840.00,126570.0,14310.00,8950.00,13860.0,14860.00,119180.00,76820.0,1050.00,3250.00,1240.00,16390.0,76900.0,54300.0,4470.00,6230.0,10960.00,32810.0,21520.0,29580.0,7720.0,22080.0,20340.0,15370.00,42390.0,300.0,44230.0,25320.0,55440.0,61950.0,90520.0,25690.00,56160.00,7550.00,8880.00,17120.00,0.00,38000.00,21270.00,59260.00,12950.00,92790.0,4730.00,3090.00,99990.0,20.00,3700.00,3560.00,10350.0,390.00,520.0,1860.00,220.00,210.0,860.0,1050.00,7000.00,57300.0,10730.00,5680.00,6400.0,10880.0,30150.0,53270.0,3130.00,2700.0,4910.00,8650.0,58680.0,2210.00,6270.0,8630.0,44240.0
PD_P_198384,3070.00,14350.00,20040.00,160820.0,15870.00,10460.00,20140.0,16160.00,156100.00,105490.0,960.00,4000.00,1840.00,24420.0,127720.0,114440.0,3510.00,4170.0,15680.00,126310.0,101070.0,91940.0,7630.0,23240.0,21730.0,21160.00,49500.0,270.0,42120.0,20080.0,97570.0,162250.0,152580.0,27870.00,74110.00,9050.00,13180.00,22800.00,0.00,41710.00,21480.00,77890.00,17020.00,130100.0,6200.00,3500.00,127120.0,0.00,3750.00,3600.00,10380.0,330.00,380.0,3080.00,250.00,530.0,1310.0,1210.00,7000.00,64240.0,10000.00,4650.00,7930.0,14570.0,66900.0,60260.0,2650.00,2890.0,4940.00,10380.0,75600.0,2580.00,5940.0,5760.0,77150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BW_A_201314,120.00,56.00,25.00,1270.0,18.00,17.00,0.0,35.00,70.00,400.0,230.00,105.00,700.00,20.0,0.0,0.0,430.00,19.0,532.00,0.0,0.0,0.0,0.0,605.0,0.0,54.00,5.0,0.0,200.0,0.0,0.0,0.0,0.0,170.00,0.00,393.00,19.00,191.00,225.00,14.00,230.00,200.00,448.00,0.0,210.00,275.00,0.0,585.00,58.00,38.00,80.0,680.00,506.0,85.00,105.00,670.0,0.0,122.00,13.00,20.0,65.00,19.00,27.0,0.0,0.0,0.0,7.00,0.0,7.00,12.0,25.0,100.00,0.0,0.0,0.0
BW_Y_201011,0.00,700.00,714.29,1000.0,0.00,700.00,500.0,750.00,0.00,1000.0,600.00,850.00,625.00,950.0,0.0,0.0,0.00,1000.0,495.24,0.0,0.0,0.0,0.0,0.0,0.0,500.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,600.00,1107.14,1000.00,842.11,911.46,1402.44,777.78,550.00,909.09,941.30,0.0,1046.15,982.14,0.0,1660.87,0.00,831.18,1100.0,1500.00,0.0,0.00,948.55,700.0,0.0,0.00,1100.00,0.0,1100.00,0.00,0.0,1100.0,0.0,0.0,0.00,0.0,750.00,0.0,0.0,799.07,0.0,0.0,0.0
BW_Y_201112,1096.77,700.00,714.29,1000.0,550.00,714.29,0.0,742.86,953.85,930.0,700.00,870.00,600.00,950.0,0.0,0.0,900.00,1000.0,500.00,0.0,0.0,0.0,450.0,1220.0,0.0,600.00,0.0,0.0,1000.0,0.0,0.0,0.0,0.0,1060.00,0.00,1000.00,842.11,963.35,2131.71,777.78,634.15,613.64,937.78,0.0,1585.37,898.46,0.0,1660.87,961.54,942.86,1000.0,1000.00,1000.0,764.71,764.71,900.0,0.0,532.79,807.69,0.0,1066.67,1100.00,700.0,0.0,0.0,0.0,1600.00,0.0,514.29,1500.0,1000.0,850.00,0.0,0.0,0.0
BW_Y_201213,1398.00,643.00,680.00,1000.0,556.00,706.00,0.0,800.00,1000.00,950.0,600.00,867.00,570.00,1000.0,0.0,0.0,891.00,1000.0,506.00,0.0,0.0,0.0,0.0,800.0,0.0,1000.00,1000.0,0.0,1000.0,0.0,0.0,0.0,0.0,1060.00,0.00,1008.00,895.00,963.00,2023.00,1143.00,651.00,605.00,931.00,0.0,1030.00,891.00,0.0,1661.00,962.00,974.00,1451.0,899.00,1000.0,1000.00,1410.00,900.0,0.0,533.00,846.00,0.0,1067.00,1107.00,690.0,0.0,0.0,0.0,1571.00,0.0,571.00,1600.0,1000.0,800.00,0.0,0.0,0.0
BW_Y_201314,1416.67,642.86,800.00,1000.0,833.33,705.88,0.0,857.14,1000.00,1000.0,652.17,857.14,571.43,1000.0,0.0,0.0,906.98,1000.0,511.28,0.0,0.0,0.0,0.0,1000.0,0.0,981.48,1000.0,0.0,1130.0,0.0,0.0,0.0,0.0,1111.76,0.00,1007.63,1000.00,979.06,1577.78,1142.86,747.83,635.00,933.04,0.0,1200.00,872.73,0.0,1743.59,1689.66,973.68,1450.0,1014.71,1000.0,1000.00,1476.19,900.0,0.0,983.61,1153.85,0.0,1092.31,1052.63,703.7,0.0,0.0,0.0,1857.14,0.0,571.43,1000.0,1000.0,820.00,0.0,0.0,0.0

The crop name(paddy, wheat, maize, millet, barley), stat type(production, area, yield) and the fiscal year are all in the same 'YEAR' column. They need to be separeted. Let's make functions to separate them below.

In [20]:
def get_crop(col):
    return {
        'PD': 'Paddy',
        'WT': 'Wheat',
        'MZ': 'Maize',
        'ML': 'Millet',
        'BL': 'Barley',
        'BW': 'Buckwheat'
    }[col.split('_')[0]]


def get_stats_type(col):
    return {
        'P': 'Production',
        'A': 'Area',
        'Y': 'Yield',
    }[col.split('_')[1]]


def get_year(col):
    year = col.split('_')[2][:4]
    return f'{year}/{int(year) + 1}'

In [21]:
crop_df['Crop'] = crop_df.index.map(get_crop) #Add a 'Crop' column containing the corresponding crops
crop_df['Stat_Type'] = crop_df.index.map(get_stats_type) #Add a 'Stat_Type' column containing the corresponding stat type.
crop_df.index = crop_df.index.map(get_year) #Change the year column so that it contains only the fiscal year
crop_df

Year,Taplejung,Panchthar,Ilam,Jhapa,Sankhuwasabha,Bhojpur,Dhankuta,Tehrathum,Morang,Sunsari,Solukhumbu,Okhaldhunga,Khotang,Udayapur,Saptari,Siraha,Dolakha,Ramechhap,Sindhuli,Dhanusa,Mahottari,Sarlahi,Sindhupalchok,Kavre,Bhaktapur,Lalitpur,Kathmandu,Rasuwa,Nuwakot,Dhading,Rautahat,Bara,Parsa,Makwanpur,Chitwan,Gorkha,Lamjung,Tanahu,Manang,Kaski,Syangja,Nawalparasi,Palpa,Rupandehi,Gulmi,Arghakhanchi,Kapilbastu,Mustang,Myagdi,Parbat,Baglung,Dolpa,Mugu,Jumla,Kalikot,Humla,Rukum,Rolpa,Pyuthan,Dang,Salyan,Jajarkot,Dailekh,Surkhet,Banke,Bardiya,Bajura,Achham,Bajhang,Doti,Kailali,Darchula,Baitadi,Dadeldhura,Kanchanpur,Crop,Stat_Type
1979/1980,3320.00,7180.00,18700.00,148020.0,20260.00,10400.00,16080.0,6960.00,139760.00,91390.0,440.00,4200.00,2420.00,25920.0,144240.0,133490.0,3500.00,7780.0,19530.00,100930.0,113120.0,54840.0,7170.0,16400.0,17360.0,15090.00,37420.0,190.0,16940.0,11790.0,108270.0,106440.0,78270.0,19710.00,45500.00,7560.00,10240.00,18600.00,0.00,23280.00,18620.00,53020.00,7050.00,76150.0,6170.00,3730.00,55320.0,150.00,4300.00,3490.00,3710.0,320.00,350.0,2340.00,380.00,360.0,1280.0,1110.00,6080.00,36930.0,6040.00,5040.00,5320.0,7520.0,26000.0,37930.0,5210.00,2540.0,4590.00,8570.0,32670.0,2380.00,3910.0,1710.0,16930.0,Paddy,Production
1980/1981,3400.00,7000.00,27530.00,152250.0,18480.00,12250.00,18440.0,8000.00,141100.00,91500.0,500.00,4600.00,2500.00,26160.0,145450.0,134250.0,3290.00,9000.0,19680.00,104200.0,122850.0,63650.0,7100.0,16030.0,21450.0,14960.00,35280.0,390.0,17000.0,13490.0,119050.0,108900.0,84610.0,22510.00,48190.00,8550.00,11220.00,17950.00,0.00,23500.00,19000.00,70770.00,11400.00,129660.0,6300.00,4100.00,139610.0,30.00,4000.00,3520.00,5590.0,240.00,560.0,2700.00,430.00,210.0,1640.0,1140.00,7000.00,60080.0,8570.00,5710.00,6120.0,12860.0,52120.0,60200.0,3260.00,3600.0,4510.00,10400.0,86700.0,2190.00,6570.0,3600.0,43660.0,Paddy,Production
1981/1982,3570.00,5680.00,30290.00,137070.0,18480.00,14640.00,19370.0,17750.00,152890.00,107360.0,950.00,4250.00,2380.00,23040.0,104080.0,112220.0,3840.00,7550.0,16540.00,98060.0,126020.0,73850.0,7100.0,18050.0,28700.0,18950.00,52530.0,320.0,24630.0,20820.0,109030.0,140940.0,132000.0,19770.00,62000.00,8790.00,10590.00,28130.00,0.00,41920.00,21850.00,62470.00,15750.00,99370.0,6360.00,3580.00,141250.0,20.00,3780.00,3560.00,7550.0,390.00,560.0,3480.00,430.00,240.0,1640.0,1140.00,7000.00,56680.0,8570.00,5740.00,7530.0,13570.0,56850.0,60130.0,3200.00,3770.0,5180.00,13150.0,73790.0,2300.00,6600.0,3450.0,55000.0,Paddy,Production
1982/1983,3010.00,3810.00,15840.00,126570.0,14310.00,8950.00,13860.0,14860.00,119180.00,76820.0,1050.00,3250.00,1240.00,16390.0,76900.0,54300.0,4470.00,6230.0,10960.00,32810.0,21520.0,29580.0,7720.0,22080.0,20340.0,15370.00,42390.0,300.0,44230.0,25320.0,55440.0,61950.0,90520.0,25690.00,56160.00,7550.00,8880.00,17120.00,0.00,38000.00,21270.00,59260.00,12950.00,92790.0,4730.00,3090.00,99990.0,20.00,3700.00,3560.00,10350.0,390.00,520.0,1860.00,220.00,210.0,860.0,1050.00,7000.00,57300.0,10730.00,5680.00,6400.0,10880.0,30150.0,53270.0,3130.00,2700.0,4910.00,8650.0,58680.0,2210.00,6270.0,8630.0,44240.0,Paddy,Production
1983/1984,3070.00,14350.00,20040.00,160820.0,15870.00,10460.00,20140.0,16160.00,156100.00,105490.0,960.00,4000.00,1840.00,24420.0,127720.0,114440.0,3510.00,4170.0,15680.00,126310.0,101070.0,91940.0,7630.0,23240.0,21730.0,21160.00,49500.0,270.0,42120.0,20080.0,97570.0,162250.0,152580.0,27870.00,74110.00,9050.00,13180.00,22800.00,0.00,41710.00,21480.00,77890.00,17020.00,130100.0,6200.00,3500.00,127120.0,0.00,3750.00,3600.00,10380.0,330.00,380.0,3080.00,250.00,530.0,1310.0,1210.00,7000.00,64240.0,10000.00,4650.00,7930.0,14570.0,66900.0,60260.0,2650.00,2890.0,4940.00,10380.0,75600.0,2580.00,5940.0,5760.0,77150.0,Paddy,Production
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013/2014,120.00,56.00,25.00,1270.0,18.00,17.00,0.0,35.00,70.00,400.0,230.00,105.00,700.00,20.0,0.0,0.0,430.00,19.0,532.00,0.0,0.0,0.0,0.0,605.0,0.0,54.00,5.0,0.0,200.0,0.0,0.0,0.0,0.0,170.00,0.00,393.00,19.00,191.00,225.00,14.00,230.00,200.00,448.00,0.0,210.00,275.00,0.0,585.00,58.00,38.00,80.0,680.00,506.0,85.00,105.00,670.0,0.0,122.00,13.00,20.0,65.00,19.00,27.0,0.0,0.0,0.0,7.00,0.0,7.00,12.0,25.0,100.00,0.0,0.0,0.0,Buckwheat,Area
2010/2011,0.00,700.00,714.29,1000.0,0.00,700.00,500.0,750.00,0.00,1000.0,600.00,850.00,625.00,950.0,0.0,0.0,0.00,1000.0,495.24,0.0,0.0,0.0,0.0,0.0,0.0,500.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,600.00,1107.14,1000.00,842.11,911.46,1402.44,777.78,550.00,909.09,941.30,0.0,1046.15,982.14,0.0,1660.87,0.00,831.18,1100.0,1500.00,0.0,0.00,948.55,700.0,0.0,0.00,1100.00,0.0,1100.00,0.00,0.0,1100.0,0.0,0.0,0.00,0.0,750.00,0.0,0.0,799.07,0.0,0.0,0.0,Buckwheat,Yield
2011/2012,1096.77,700.00,714.29,1000.0,550.00,714.29,0.0,742.86,953.85,930.0,700.00,870.00,600.00,950.0,0.0,0.0,900.00,1000.0,500.00,0.0,0.0,0.0,450.0,1220.0,0.0,600.00,0.0,0.0,1000.0,0.0,0.0,0.0,0.0,1060.00,0.00,1000.00,842.11,963.35,2131.71,777.78,634.15,613.64,937.78,0.0,1585.37,898.46,0.0,1660.87,961.54,942.86,1000.0,1000.00,1000.0,764.71,764.71,900.0,0.0,532.79,807.69,0.0,1066.67,1100.00,700.0,0.0,0.0,0.0,1600.00,0.0,514.29,1500.0,1000.0,850.00,0.0,0.0,0.0,Buckwheat,Yield
2012/2013,1398.00,643.00,680.00,1000.0,556.00,706.00,0.0,800.00,1000.00,950.0,600.00,867.00,570.00,1000.0,0.0,0.0,891.00,1000.0,506.00,0.0,0.0,0.0,0.0,800.0,0.0,1000.00,1000.0,0.0,1000.0,0.0,0.0,0.0,0.0,1060.00,0.00,1008.00,895.00,963.00,2023.00,1143.00,651.00,605.00,931.00,0.0,1030.00,891.00,0.0,1661.00,962.00,974.00,1451.0,899.00,1000.0,1000.00,1410.00,900.0,0.0,533.00,846.00,0.0,1067.00,1107.00,690.0,0.0,0.0,0.0,1571.00,0.0,571.00,1600.0,1000.0,800.00,0.0,0.0,0.0,Buckwheat,Yield
2013/2014,1416.67,642.86,800.00,1000.0,833.33,705.88,0.0,857.14,1000.00,1000.0,652.17,857.14,571.43,1000.0,0.0,0.0,906.98,1000.0,511.28,0.0,0.0,0.0,0.0,1000.0,0.0,981.48,1000.0,0.0,1130.0,0.0,0.0,0.0,0.0,1111.76,0.00,1007.63,1000.00,979.06,1577.78,1142.86,747.83,635.00,933.04,0.0,1200.00,872.73,0.0,1743.59,1689.66,973.68,1450.0,1014.71,1000.0,1000.00,1476.19,900.0,0.0,983.61,1153.85,0.0,1092.31,1052.63,703.7,0.0,0.0,0.0,1857.14,0.0,571.43,1000.0,1000.0,820.00,0.0,0.0,0.0,Buckwheat,Yield

In [22]:
crop_df.reset_index(inplace=True) #reset the index so that 'Year' column is no longer the index
crop_df.rename(columns={'index':'Year'}, inplace=True) #Rename the column 'index' to 'Year'
crop_df

Year,Year,Taplejung,Panchthar,Ilam,Jhapa,Sankhuwasabha,Bhojpur,Dhankuta,Tehrathum,Morang,Sunsari,Solukhumbu,Okhaldhunga,Khotang,Udayapur,Saptari,Siraha,Dolakha,Ramechhap,Sindhuli,Dhanusa,Mahottari,Sarlahi,Sindhupalchok,Kavre,Bhaktapur,Lalitpur,Kathmandu,Rasuwa,Nuwakot,Dhading,Rautahat,Bara,Parsa,Makwanpur,Chitwan,Gorkha,Lamjung,Tanahu,Manang,Kaski,Syangja,Nawalparasi,Palpa,Rupandehi,Gulmi,Arghakhanchi,Kapilbastu,Mustang,Myagdi,Parbat,Baglung,Dolpa,Mugu,Jumla,Kalikot,Humla,Rukum,Rolpa,Pyuthan,Dang,Salyan,Jajarkot,Dailekh,Surkhet,Banke,Bardiya,Bajura,Achham,Bajhang,Doti,Kailali,Darchula,Baitadi,Dadeldhura,Kanchanpur,Crop,Stat_Type
0,1979/1980,3320.00,7180.00,18700.00,148020.0,20260.00,10400.00,16080.0,6960.00,139760.00,91390.0,440.00,4200.00,2420.00,25920.0,144240.0,133490.0,3500.00,7780.0,19530.00,100930.0,113120.0,54840.0,7170.0,16400.0,17360.0,15090.00,37420.0,190.0,16940.0,11790.0,108270.0,106440.0,78270.0,19710.00,45500.00,7560.00,10240.00,18600.00,0.00,23280.00,18620.00,53020.00,7050.00,76150.0,6170.00,3730.00,55320.0,150.00,4300.00,3490.00,3710.0,320.00,350.0,2340.00,380.00,360.0,1280.0,1110.00,6080.00,36930.0,6040.00,5040.00,5320.0,7520.0,26000.0,37930.0,5210.00,2540.0,4590.00,8570.0,32670.0,2380.00,3910.0,1710.0,16930.0,Paddy,Production
1,1980/1981,3400.00,7000.00,27530.00,152250.0,18480.00,12250.00,18440.0,8000.00,141100.00,91500.0,500.00,4600.00,2500.00,26160.0,145450.0,134250.0,3290.00,9000.0,19680.00,104200.0,122850.0,63650.0,7100.0,16030.0,21450.0,14960.00,35280.0,390.0,17000.0,13490.0,119050.0,108900.0,84610.0,22510.00,48190.00,8550.00,11220.00,17950.00,0.00,23500.00,19000.00,70770.00,11400.00,129660.0,6300.00,4100.00,139610.0,30.00,4000.00,3520.00,5590.0,240.00,560.0,2700.00,430.00,210.0,1640.0,1140.00,7000.00,60080.0,8570.00,5710.00,6120.0,12860.0,52120.0,60200.0,3260.00,3600.0,4510.00,10400.0,86700.0,2190.00,6570.0,3600.0,43660.0,Paddy,Production
2,1981/1982,3570.00,5680.00,30290.00,137070.0,18480.00,14640.00,19370.0,17750.00,152890.00,107360.0,950.00,4250.00,2380.00,23040.0,104080.0,112220.0,3840.00,7550.0,16540.00,98060.0,126020.0,73850.0,7100.0,18050.0,28700.0,18950.00,52530.0,320.0,24630.0,20820.0,109030.0,140940.0,132000.0,19770.00,62000.00,8790.00,10590.00,28130.00,0.00,41920.00,21850.00,62470.00,15750.00,99370.0,6360.00,3580.00,141250.0,20.00,3780.00,3560.00,7550.0,390.00,560.0,3480.00,430.00,240.0,1640.0,1140.00,7000.00,56680.0,8570.00,5740.00,7530.0,13570.0,56850.0,60130.0,3200.00,3770.0,5180.00,13150.0,73790.0,2300.00,6600.0,3450.0,55000.0,Paddy,Production
3,1982/1983,3010.00,3810.00,15840.00,126570.0,14310.00,8950.00,13860.0,14860.00,119180.00,76820.0,1050.00,3250.00,1240.00,16390.0,76900.0,54300.0,4470.00,6230.0,10960.00,32810.0,21520.0,29580.0,7720.0,22080.0,20340.0,15370.00,42390.0,300.0,44230.0,25320.0,55440.0,61950.0,90520.0,25690.00,56160.00,7550.00,8880.00,17120.00,0.00,38000.00,21270.00,59260.00,12950.00,92790.0,4730.00,3090.00,99990.0,20.00,3700.00,3560.00,10350.0,390.00,520.0,1860.00,220.00,210.0,860.0,1050.00,7000.00,57300.0,10730.00,5680.00,6400.0,10880.0,30150.0,53270.0,3130.00,2700.0,4910.00,8650.0,58680.0,2210.00,6270.0,8630.0,44240.0,Paddy,Production
4,1983/1984,3070.00,14350.00,20040.00,160820.0,15870.00,10460.00,20140.0,16160.00,156100.00,105490.0,960.00,4000.00,1840.00,24420.0,127720.0,114440.0,3510.00,4170.0,15680.00,126310.0,101070.0,91940.0,7630.0,23240.0,21730.0,21160.00,49500.0,270.0,42120.0,20080.0,97570.0,162250.0,152580.0,27870.00,74110.00,9050.00,13180.00,22800.00,0.00,41710.00,21480.00,77890.00,17020.00,130100.0,6200.00,3500.00,127120.0,0.00,3750.00,3600.00,10380.0,330.00,380.0,3080.00,250.00,530.0,1310.0,1210.00,7000.00,64240.0,10000.00,4650.00,7930.0,14570.0,66900.0,60260.0,2650.00,2890.0,4940.00,10380.0,75600.0,2580.00,5940.0,5760.0,77150.0,Paddy,Production
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,2013/2014,120.00,56.00,25.00,1270.0,18.00,17.00,0.0,35.00,70.00,400.0,230.00,105.00,700.00,20.0,0.0,0.0,430.00,19.0,532.00,0.0,0.0,0.0,0.0,605.0,0.0,54.00,5.0,0.0,200.0,0.0,0.0,0.0,0.0,170.00,0.00,393.00,19.00,191.00,225.00,14.00,230.00,200.00,448.00,0.0,210.00,275.00,0.0,585.00,58.00,38.00,80.0,680.00,506.0,85.00,105.00,670.0,0.0,122.00,13.00,20.0,65.00,19.00,27.0,0.0,0.0,0.0,7.00,0.0,7.00,12.0,25.0,100.00,0.0,0.0,0.0,Buckwheat,Area
518,2010/2011,0.00,700.00,714.29,1000.0,0.00,700.00,500.0,750.00,0.00,1000.0,600.00,850.00,625.00,950.0,0.0,0.0,0.00,1000.0,495.24,0.0,0.0,0.0,0.0,0.0,0.0,500.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,600.00,1107.14,1000.00,842.11,911.46,1402.44,777.78,550.00,909.09,941.30,0.0,1046.15,982.14,0.0,1660.87,0.00,831.18,1100.0,1500.00,0.0,0.00,948.55,700.0,0.0,0.00,1100.00,0.0,1100.00,0.00,0.0,1100.0,0.0,0.0,0.00,0.0,750.00,0.0,0.0,799.07,0.0,0.0,0.0,Buckwheat,Yield
519,2011/2012,1096.77,700.00,714.29,1000.0,550.00,714.29,0.0,742.86,953.85,930.0,700.00,870.00,600.00,950.0,0.0,0.0,900.00,1000.0,500.00,0.0,0.0,0.0,450.0,1220.0,0.0,600.00,0.0,0.0,1000.0,0.0,0.0,0.0,0.0,1060.00,0.00,1000.00,842.11,963.35,2131.71,777.78,634.15,613.64,937.78,0.0,1585.37,898.46,0.0,1660.87,961.54,942.86,1000.0,1000.00,1000.0,764.71,764.71,900.0,0.0,532.79,807.69,0.0,1066.67,1100.00,700.0,0.0,0.0,0.0,1600.00,0.0,514.29,1500.0,1000.0,850.00,0.0,0.0,0.0,Buckwheat,Yield
520,2012/2013,1398.00,643.00,680.00,1000.0,556.00,706.00,0.0,800.00,1000.00,950.0,600.00,867.00,570.00,1000.0,0.0,0.0,891.00,1000.0,506.00,0.0,0.0,0.0,0.0,800.0,0.0,1000.00,1000.0,0.0,1000.0,0.0,0.0,0.0,0.0,1060.00,0.00,1008.00,895.00,963.00,2023.00,1143.00,651.00,605.00,931.00,0.0,1030.00,891.00,0.0,1661.00,962.00,974.00,1451.0,899.00,1000.0,1000.00,1410.00,900.0,0.0,533.00,846.00,0.0,1067.00,1107.00,690.0,0.0,0.0,0.0,1571.00,0.0,571.00,1600.0,1000.0,800.00,0.0,0.0,0.0,Buckwheat,Yield
521,2013/2014,1416.67,642.86,800.00,1000.0,833.33,705.88,0.0,857.14,1000.00,1000.0,652.17,857.14,571.43,1000.0,0.0,0.0,906.98,1000.0,511.28,0.0,0.0,0.0,0.0,1000.0,0.0,981.48,1000.0,0.0,1130.0,0.0,0.0,0.0,0.0,1111.76,0.00,1007.63,1000.00,979.06,1577.78,1142.86,747.83,635.00,933.04,0.0,1200.00,872.73,0.0,1743.59,1689.66,973.68,1450.0,1014.71,1000.0,1000.00,1476.19,900.0,0.0,983.61,1153.85,0.0,1092.31,1052.63,703.7,0.0,0.0,0.0,1857.14,0.0,571.43,1000.0,1000.0,820.00,0.0,0.0,0.0,Buckwheat,Yield

In [23]:
#Change all the columns except 'Year', 'Crop' and 'Stat_Type' into values of a single column named 'District' and
#all the corresponding values in a column named 'Value'
crop_df = crop_df.melt(id_vars=['Year', 'Crop', 'Stat_Type'],
                       var_name='District',
                       value_name='Value')
crop_df

            Year       Crop   Stat_Type    District   Value
0      1979/1980      Paddy  Production   Taplejung  3320.0
1      1980/1981      Paddy  Production   Taplejung  3400.0
2      1981/1982      Paddy  Production   Taplejung  3570.0
3      1982/1983      Paddy  Production   Taplejung  3010.0
4      1983/1984      Paddy  Production   Taplejung  3070.0
...          ...        ...         ...         ...     ...
39145  2013/2014  Buckwheat        Area  Kanchanpur     0.0
39146  2010/2011  Buckwheat       Yield  Kanchanpur     0.0
39147  2011/2012  Buckwheat       Yield  Kanchanpur     0.0
39148  2012/2013  Buckwheat       Yield  Kanchanpur     0.0
39149  2013/2014  Buckwheat       Yield  Kanchanpur     0.0

[39150 rows x 5 columns]

In [24]:
#Make each value of 'Stat_Type' into a separate column with 'Year', 'District' and 'Crop' as index and the values
#in the column 'Value' as values
crop_df = crop_df.pivot_table(index=['Year', 'District', 'Crop'], columns='Stat_Type', values='Value')
crop_df

Stat_Type                        Area  Production   Yield
Year      District Crop
1979/1980 Achham   Barley       550.0       500.0   909.0
                   Maize       3100.0      4920.0  1587.0
                   Millet       900.0      1000.0  1111.0
                   Paddy       2450.0      2540.0  1037.0
                   Wheat       2850.0      2600.0   912.0
...                               ...         ...     ...
2013/2014 Udayapur Buckwheat     20.0        20.0  1000.0
                   Maize       9500.0     23500.0  2474.0
                   Millet      2580.0      5000.0  1938.0
                   Paddy      15250.0     52850.0  3466.0
                   Wheat       5120.0     15826.0  3091.0

[13050 rows x 3 columns]

In [25]:
#remove the column 'Crop' from index.
crop_df = crop_df.reset_index('Crop')
crop_df

Stat_Type                Crop     Area  Production   Yield
Year      District
1979/1980 Achham       Barley    550.0       500.0   909.0
          Achham        Maize   3100.0      4920.0  1587.0
          Achham       Millet    900.0      1000.0  1111.0
          Achham        Paddy   2450.0      2540.0  1037.0
          Achham        Wheat   2850.0      2600.0   912.0
...                       ...      ...         ...     ...
2013/2014 Udayapur  Buckwheat     20.0        20.0  1000.0
          Udayapur      Maize   9500.0     23500.0  2474.0
          Udayapur     Millet   2580.0      5000.0  1938.0
          Udayapur      Paddy  15250.0     52850.0  3466.0
          Udayapur      Wheat   5120.0     15826.0  3091.0

[13050 rows x 4 columns]

In [26]:
crop_df.columns

Index(['Crop', 'Area', 'Production', 'Yield'], dtype='object', name='Stat_Type')

In [27]:
crop_df.columns.values

array(['Crop', 'Area', 'Production', 'Yield'], dtype=object)

In [28]:
crop_df.columns = crop_df.columns.values
crop_df

                         Crop     Area  Production   Yield
Year      District
1979/1980 Achham       Barley    550.0       500.0   909.0
          Achham        Maize   3100.0      4920.0  1587.0
          Achham       Millet    900.0      1000.0  1111.0
          Achham        Paddy   2450.0      2540.0  1037.0
          Achham        Wheat   2850.0      2600.0   912.0
...                       ...      ...         ...     ...
2013/2014 Udayapur  Buckwheat     20.0        20.0  1000.0
          Udayapur      Maize   9500.0     23500.0  2474.0
          Udayapur     Millet   2580.0      5000.0  1938.0
          Udayapur      Paddy  15250.0     52850.0  3466.0
          Udayapur      Wheat   5120.0     15826.0  3091.0

[13050 rows x 4 columns]

## Merge crop and climate data

In [29]:
display(crop_df)
display(climate_df)

                         Crop     Area  Production   Yield
Year      District
1979/1980 Achham       Barley    550.0       500.0   909.0
          Achham        Maize   3100.0      4920.0  1587.0
          Achham       Millet    900.0      1000.0  1111.0
          Achham        Paddy   2450.0      2540.0  1037.0
          Achham        Wheat   2850.0      2600.0   912.0
...                       ...      ...         ...     ...
2013/2014 Udayapur  Buckwheat     20.0        20.0  1000.0
          Udayapur      Maize   9500.0     23500.0  2474.0
          Udayapur     Millet   2580.0      5000.0  1938.0
          Udayapur      Paddy  15250.0     52850.0  3466.0
          Udayapur      Wheat   5120.0     15826.0  3091.0

[13050 rows x 4 columns]

                          LAT   LON  PRECTOT         PS       QV2M       RH2M  \
Year      District
1982/1983 Achham        29.11  81.3   665.15  87.577863   7.857616  47.294082
          Arghakhanchi  27.90  83.2   810.13  93.133123   8.912356  45.122137
          Baglung       28.30  83.6   701.53  79.262877   7.262740  53.903781
          Baitadi       29.50  80.5   498.34  73.814658   5.931178  52.656329
          Bajhang       29.60  81.2   413.81  67.878877   5.163945  56.509452
...                       ...   ...      ...        ...        ...        ...
2018/2019 Syangja       28.00  83.8  1594.53  86.005945   9.939973  62.634192
          Tanahu        28.00  84.1  1529.04  77.660274   8.610411  69.434959
          Taplejung     27.40  87.7  1373.49  80.040219   9.461699  70.148384
          Tehrathum     27.10  87.5  1373.49  80.040219   9.461699  70.148384
          Udayapur      26.90  86.5  1239.51  95.006329  11.662301  56.259452

                              T2M     T2MWET    T2M_MAX    T2M_MIN         TS  \
Year      District
1982/1983 Achham        19.098575  12.374877  25.967479  13.345041  18.361644
          Arghakhanchi  22.478137   8.292548  28.893479  17.407589  22.155562
          Baglung       13.294795   2.833507  19.143616   8.798411  12.878822
          Baitadi        9.178027  -0.891918  15.637370   4.054356   9.069890
          Bajhang        4.649507  -3.767753  11.253288  -0.529178   4.983726
...                           ...        ...        ...        ...        ...
2018/2019 Syangja       17.612219   9.306055  23.026055  13.293233  16.915151
          Tanahu        11.862795   5.320630  16.867918   7.775452  11.225616
          Taplejung     13.748740   7.436274  18.993726   9.745589  13.408384
          Tehrathum     13.748740   7.436274  18.993726   9.745589  13.408384
          Udayapur      23.685315  13.602301  29.383808  19.167315  23.455123

                           WS10M  WS10M_MAX  WS10M_MIN     WS50M  WS50M_MAX  \
Year      District
1982/1983 Achham        2.249288   4.393726   0.452164  2.645753   4.543562
          Arghakhanchi  2.677178   4.695863   1.026274  3.636767   5.479644
          Baglung       2.222658   4.849507   0.400932  2.236959   4.241425
          Baitadi       2.310849   5.084301   0.372521  2.273534   4.490548
          Bajhang       2.536274   5.789041   0.458411  2.493205   5.191918
...                          ...        ...        ...       ...        ...
2018/2019 Syangja       2.160740   4.079753   0.611589  2.591151   4.280301
          Tanahu        2.063068   4.260274   0.351096  2.014000   3.590274
          Taplejung     2.129644   4.611151   0.388466  2.209945   4.192712
          Tehrathum     2.129644   4.611151   0.388466  2.209945   4.192712
          Udayapur      2.515425   4.312219   0.997123  3.369534   5.010685

                        WS50M_MIN  T2M_RANGE  WS10M_RANGE  WS50M_RANGE
Year      District
1982/1983 Achham         0.574247  12.622438     3.941562     3.969315
          Arghakhanchi   1.399452  11.485890     3.669589     4.080192
          Baglung        0.515123  10.345205     4.448575     3.726301
          Baitadi        0.465808  11.583014     4.711781     4.024740
          Bajhang        0.567151  11.782466     5.330630     4.624767
...                           ...        ...          ...          ...
2018/2019 Syangja        0.831425   9.732822     3.468164     3.448877
          Tanahu         0.446822   9.092466     3.909178     3.143452
          Taplejung      0.540110   9.248137     4.222685     3.652603
          Tehrathum      0.540110   9.248137     4.222685     3.652603
          Udayapur       1.510685  10.216493     3.315096     3.500000

[2775 rows x 20 columns]

In [30]:
data = climate_df.join(crop_df, how='inner')
data

                      LAT   LON  PRECTOT         PS       QV2M       RH2M  \
Year      District
1982/1983 Achham    29.11  81.3   665.15  87.577863   7.857616  47.294082
          Achham    29.11  81.3   665.15  87.577863   7.857616  47.294082
          Achham    29.11  81.3   665.15  87.577863   7.857616  47.294082
          Achham    29.11  81.3   665.15  87.577863   7.857616  47.294082
          Achham    29.11  81.3   665.15  87.577863   7.857616  47.294082
...                   ...   ...      ...        ...        ...        ...
2013/2014 Udayapur  26.90  86.5  1091.43  94.958986  11.648603  59.332767
          Udayapur  26.90  86.5  1091.43  94.958986  11.648603  59.332767
          Udayapur  26.90  86.5  1091.43  94.958986  11.648603  59.332767
          Udayapur  26.90  86.5  1091.43  94.958986  11.648603  59.332767
          Udayapur  26.90  86.5  1091.43  94.958986  11.648603  59.332767

                          T2M     T2MWET    T2M_MAX    T2M_MIN         TS  \
Year      District
1982/1983 Achham    19.098575  12.374877  25.967479  13.345041  18.361644
          Achham    19.098575  12.374877  25.967479  13.345041  18.361644
          Achham    19.098575  12.374877  25.967479  13.345041  18.361644
          Achham    19.098575  12.374877  25.967479  13.345041  18.361644
          Achham    19.098575  12.374877  25.967479  13.345041  18.361644
...                       ...        ...        ...        ...        ...
2013/2014 Udayapur  23.291014  13.583370  28.945288  18.873068  23.081616
          Udayapur  23.291014  13.583370  28.945288  18.873068  23.081616
          Udayapur  23.291014  13.583370  28.945288  18.873068  23.081616
          Udayapur  23.291014  13.583370  28.945288  18.873068  23.081616
          Udayapur  23.291014  13.583370  28.945288  18.873068  23.081616

                       WS10M  WS10M_MAX  WS10M_MIN     WS50M  WS50M_MAX  \
Year      District
1982/1983 Achham    2.249288   4.393726   0.452164  2.645753   4.543562
          Achham    2.249288   4.393726   0.452164  2.645753   4.543562
          Achham    2.249288   4.393726   0.452164  2.645753   4.543562
          Achham    2.249288   4.393726   0.452164  2.645753   4.543562
          Achham    2.249288   4.393726   0.452164  2.645753   4.543562
...                      ...        ...        ...       ...        ...
2013/2014 Udayapur  2.395068   4.262548   0.874548  3.231425   4.951151
          Udayapur  2.395068   4.262548   0.874548  3.231425   4.951151
          Udayapur  2.395068   4.262548   0.874548  3.231425   4.951151
          Udayapur  2.395068   4.262548   0.874548  3.231425   4.951151
          Udayapur  2.395068   4.262548   0.874548  3.231425   4.951151

                    WS50M_MIN  T2M_RANGE  WS10M_RANGE  WS50M_RANGE       Crop  \
Year      District
1982/1983 Achham     0.574247  12.622438     3.941562     3.969315     Barley
          Achham     0.574247  12.622438     3.941562     3.969315      Maize
          Achham     0.574247  12.622438     3.941562     3.969315     Millet
          Achham     0.574247  12.622438     3.941562     3.969315      Paddy
          Achham     0.574247  12.622438     3.941562     3.969315      Wheat
...                       ...        ...          ...          ...        ...
2013/2014 Udayapur   1.284932  10.072219     3.388000     3.666219  Buckwheat
          Udayapur   1.284932  10.072219     3.388000     3.666219      Maize
          Udayapur   1.284932  10.072219     3.388000     3.666219     Millet
          Udayapur   1.284932  10.072219     3.388000     3.666219      Paddy
          Udayapur   1.284932  10.072219     3.388000     3.666219      Wheat

                       Area  Production   Yield
Year      District
1982/1983 Achham      500.0       400.0   800.0
          Achham     2850.0      3420.0  1200.0
          Achham      850.0       940.0  1106.0
          Achham     1930.0      2700.0  1399.0
          Achham     3200.0      3360.0  1050.0
...                     ...         ...     ...
2013/2014 Udayapur     20.0        20.0  1000.0
          Udayapur   9500.0     23500.0  2474.0
          Udayapur   2580.0      5000.0  1938.0
          Udayapur  15250.0     52850.0  3466.0
          Udayapur   5120.0     15826.0  3091.0

[11925 rows x 24 columns]

In [31]:
data = data.set_index('Crop', append=True) #Add 'Crop' column to the index
data

                                LAT   LON  PRECTOT         PS       QV2M  \
Year      District Crop
1982/1983 Achham   Barley     29.11  81.3   665.15  87.577863   7.857616
                   Maize      29.11  81.3   665.15  87.577863   7.857616
                   Millet     29.11  81.3   665.15  87.577863   7.857616
                   Paddy      29.11  81.3   665.15  87.577863   7.857616
                   Wheat      29.11  81.3   665.15  87.577863   7.857616
...                             ...   ...      ...        ...        ...
2013/2014 Udayapur Buckwheat  26.90  86.5  1091.43  94.958986  11.648603
                   Maize      26.90  86.5  1091.43  94.958986  11.648603
                   Millet     26.90  86.5  1091.43  94.958986  11.648603
                   Paddy      26.90  86.5  1091.43  94.958986  11.648603
                   Wheat      26.90  86.5  1091.43  94.958986  11.648603

                                   RH2M        T2M     T2MWET    T2M_MAX  \
Year      District Crop
1982/1983 Achham   Barley     47.294082  19.098575  12.374877  25.967479
                   Maize      47.294082  19.098575  12.374877  25.967479
                   Millet     47.294082  19.098575  12.374877  25.967479
                   Paddy      47.294082  19.098575  12.374877  25.967479
                   Wheat      47.294082  19.098575  12.374877  25.967479
...                                 ...        ...        ...        ...
2013/2014 Udayapur Buckwheat  59.332767  23.291014  13.583370  28.945288
                   Maize      59.332767  23.291014  13.583370  28.945288
                   Millet     59.332767  23.291014  13.583370  28.945288
                   Paddy      59.332767  23.291014  13.583370  28.945288
                   Wheat      59.332767  23.291014  13.583370  28.945288

                                T2M_MIN         TS     WS10M  WS10M_MAX  \
Year      District Crop
1982/1983 Achham   Barley     13.345041  18.361644  2.249288   4.393726
                   Maize      13.345041  18.361644  2.249288   4.393726
                   Millet     13.345041  18.361644  2.249288   4.393726
                   Paddy      13.345041  18.361644  2.249288   4.393726
                   Wheat      13.345041  18.361644  2.249288   4.393726
...                                 ...        ...       ...        ...
2013/2014 Udayapur Buckwheat  18.873068  23.081616  2.395068   4.262548
                   Maize      18.873068  23.081616  2.395068   4.262548
                   Millet     18.873068  23.081616  2.395068   4.262548
                   Paddy      18.873068  23.081616  2.395068   4.262548
                   Wheat      18.873068  23.081616  2.395068   4.262548

                              WS10M_MIN     WS50M  WS50M_MAX  WS50M_MIN  \
Year      District Crop
1982/1983 Achham   Barley      0.452164  2.645753   4.543562   0.574247
                   Maize       0.452164  2.645753   4.543562   0.574247
                   Millet      0.452164  2.645753   4.543562   0.574247
                   Paddy       0.452164  2.645753   4.543562   0.574247
                   Wheat       0.452164  2.645753   4.543562   0.574247
...                                 ...       ...        ...        ...
2013/2014 Udayapur Buckwheat   0.874548  3.231425   4.951151   1.284932
                   Maize       0.874548  3.231425   4.951151   1.284932
                   Millet      0.874548  3.231425   4.951151   1.284932
                   Paddy       0.874548  3.231425   4.951151   1.284932
                   Wheat       0.874548  3.231425   4.951151   1.284932

                              T2M_RANGE  WS10M_RANGE  WS50M_RANGE     Area  \
Year      District Crop
1982/1983 Achham   Barley     12.622438     3.941562     3.969315    500.0
                   Maize      12.622438     3.941562     3.969315   2850.0
                   Millet     12.622438     3.941562     3.969315    850.0
                   Paddy      12.622438     3.941562     3.969315   1930.0
                   Wheat      12.622438     3.941562     3.969315   3200.0
...                                 ...          ...          ...      ...
2013/2014 Udayapur Buckwheat  10.072219     3.388000     3.666219     20.0
                   Maize      10.072219     3.388000     3.666219   9500.0
                   Millet     10.072219     3.388000     3.666219   2580.0
                   Paddy      10.072219     3.388000     3.666219  15250.0
                   Wheat      10.072219     3.388000     3.666219   5120.0

                              Production   Yield
Year      District Crop
1982/1983 Achham   Barley          400.0   800.0
                   Maize          3420.0  1200.0
                   Millet          940.0  1106.0
                   Paddy          2700.0  1399.0
                   Wheat          3360.0  1050.0
...                                  ...     ...
2013/2014 Udayapur Buckwheat        20.0  1000.0
                   Maize         23500.0  2474.0
                   Millet         5000.0  1938.0
                   Paddy         52850.0  3466.0
                   Wheat         15826.0  3091.0

[11925 rows x 23 columns]

In [32]:
#Rename the columns
data.rename(columns={
    'LAT':'Latitude',
    'LON':'Longitude',
    'PRECTOT':'Precipitation(mm)',
    'PS':'Surface_Pressure(kPa)',
    'QV2M':'Specific_Humidity(g/kg)',
    'RH2M':'Relative_Humidity(%)',
    'T2M':'Temp(C)',
    'T2MWET':'Wet_Bulb_Temp(C)',
    'T2M_MAX':'Max_Temp(C)',
    'T2M_MIN':'Min_Temp(C)',
    'TS':'Earth_Skin_Temp(C)',
    'WS10M':'Wind_Speed_10M(m/s)',
    'WS10M_MAX':'Max_Wind_Speed_10M(m/s)',
    'WS10M_MIN':'Min_Wind_Speed_10M(m/s)',
    'WS50M':'Wind_Speed_50M(m/s)',
    'WS50M_MAX':'Max_Wind_Speed_50M(m/s)',
    'WS50M_MIN':'Min_Wind_Speed_50M(m/s)',
    'T2M_RANGE':'Temp_Range(C)',
    'WS10M_RANGE':'Wind_Speed_10M_Range(m/s)',
    'WS50M_RANGE':'Wind_Speed_50M_Range(m/s)',
    'Area':'Area(ha)',
    'Production':'Production(mt)',
    'Yield':'Yield(kg/ha)'
}, inplace=True)

#Reset the index
data.reset_index(names=['Year', 'District', 'Crop'], inplace=True)

pd.options.display.max_columns = 10
data

,Year,District,Crop,Latitude,Longitude,...,Wind_Speed_10M_Range(m/s),Wind_Speed_50M_Range(m/s),Area(ha),Production(mt),Yield(kg/ha)
0,1982/1983,Achham,Barley,29.11,81.3,...,3.941562,3.969315,500.0,400.0,800.0
1,1982/1983,Achham,Maize,29.11,81.3,...,3.941562,3.969315,2850.0,3420.0,1200.0
2,1982/1983,Achham,Millet,29.11,81.3,...,3.941562,3.969315,850.0,940.0,1106.0
3,1982/1983,Achham,Paddy,29.11,81.3,...,3.941562,3.969315,1930.0,2700.0,1399.0
4,1982/1983,Achham,Wheat,29.11,81.3,...,3.941562,3.969315,3200.0,3360.0,1050.0
...,...,...,...,...,...,...,...,...,...,...,...
11920,2013/2014,Udayapur,Buckwheat,26.90,86.5,...,3.388000,3.666219,20.0,20.0,1000.0
11921,2013/2014,Udayapur,Maize,26.90,86.5,...,3.388000,3.666219,9500.0,23500.0,2474.0
11922,2013/2014,Udayapur,Millet,26.90,86.5,...,3.388000,3.666219,2580.0,5000.0,1938.0
11923,2013/2014,Udayapur,Paddy,26.90,86.5,...,3.388000,3.666219,15250.0,52850.0,3466.0
11924,2013/2014,Udayapur,Wheat,26.90,86.5,...,3.388000,3.666219,5120.0,15826.0,3091.0

In [33]:
#No. of districts
len(data.District.unique())

75

In [34]:
#No. of fiscal years
len(data.Year.unique())

31

In [35]:
#No. of occurrences of each crop
data['Crop'].value_counts()

Barley       2325
Maize        2325
Millet       2325
Paddy        2325
Wheat        2325
Buckwheat     300
Name: Crop, dtype: int64

Above, we can see that Buckwheat is the least occuring crop. A quick investigation revealed that the data for Buckwheat only starts on and after the fiscal year 2010/2011. So, let us remove every data of Buckwheat from our dataset completely.

In [36]:
data = data[data['Crop'] != 'Buckwheat'] #Select only rows that does not contain 'Buckwheat' in 'Crop' column
data.reset_index(drop=True, inplace=True)
data

,Year,District,Crop,Latitude,Longitude,...,Wind_Speed_10M_Range(m/s),Wind_Speed_50M_Range(m/s),Area(ha),Production(mt),Yield(kg/ha)
0,1982/1983,Achham,Barley,29.11,81.3,...,3.941562,3.969315,500.0,400.0,800.0
1,1982/1983,Achham,Maize,29.11,81.3,...,3.941562,3.969315,2850.0,3420.0,1200.0
2,1982/1983,Achham,Millet,29.11,81.3,...,3.941562,3.969315,850.0,940.0,1106.0
3,1982/1983,Achham,Paddy,29.11,81.3,...,3.941562,3.969315,1930.0,2700.0,1399.0
4,1982/1983,Achham,Wheat,29.11,81.3,...,3.941562,3.969315,3200.0,3360.0,1050.0
...,...,...,...,...,...,...,...,...,...,...,...
11620,2013/2014,Udayapur,Barley,26.90,86.5,...,3.388000,3.666219,35.0,35.0,1000.0
11621,2013/2014,Udayapur,Maize,26.90,86.5,...,3.388000,3.666219,9500.0,23500.0,2474.0
11622,2013/2014,Udayapur,Millet,26.90,86.5,...,3.388000,3.666219,2580.0,5000.0,1938.0
11623,2013/2014,Udayapur,Paddy,26.90,86.5,...,3.388000,3.666219,15250.0,52850.0,3466.0
11624,2013/2014,Udayapur,Wheat,26.90,86.5,...,3.388000,3.666219,5120.0,15826.0,3091.0

Let's double check if the number of rows(11625) shown above is accurate. We have data from 1982/83 to 2013/14 which is 31 years. There are 75 districts and 5 crops. So, the number of rows should be equal to 31 * 75 * 5.

In [37]:
display(31*75*5) # Double Check if the number of rows is correctz

11625

## Testing

Let's drop all the DATE columns.

In [38]:
# data = data.drop(['DATE_mean', 'DATE_min', 'DATE_max'], axis=1)
# data

In [39]:
data.isnull().values.any()

False

In [41]:
0 in data.values

True

We need to convert the fiscal year in string into a numeric form. To do that, let's represent a fiscal year using the starting year of the fiscal year. For example, 1982/1983 will be represented as 1982. To do that, let's make a function below to extract the initial year from the string like 1982/1983

In [37]:
def convert_year(col):
    year = col.split('/')[0]
    return year

In [38]:
#Add a 'yr' column to the dataset which contains the initial year of the fiscal year.
data.loc[:,'yr'] = data['Year'].map(convert_year)

#Bring the 'yr' column to the front of the dataset.
data.insert(0, 'yr', data.pop('yr'))

#Drop the 'Year' column.
data = data.drop('Year', axis=1)

#Rename the 'yr' column to 'Year' column
data = data.rename(columns={'yr':'Year'})

data

/tmp/ipykernel_39071/415379082.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[:,'yr'] = data['Year'].map(convert_year)

,Year,District,Crop,Latitude,Longitude,...,Wind_Speed_10M_Range(m/s),Wind_Speed_50M_Range(m/s),Area(ha),Production(mt),Yield(kg/ha)
0,1982,Achham,Barley,29.11,81.3,...,3.941562,3.969315,500.0,400.0,800.0
1,1982,Achham,Maize,29.11,81.3,...,3.941562,3.969315,2850.0,3420.0,1200.0
2,1982,Achham,Millet,29.11,81.3,...,3.941562,3.969315,850.0,940.0,1106.0
3,1982,Achham,Paddy,29.11,81.3,...,3.941562,3.969315,1930.0,2700.0,1399.0
4,1982,Achham,Wheat,29.11,81.3,...,3.941562,3.969315,3200.0,3360.0,1050.0
...,...,...,...,...,...,...,...,...,...,...,...
11620,2013,Udayapur,Barley,26.90,86.5,...,3.388000,3.666219,35.0,35.0,1000.0
11621,2013,Udayapur,Maize,26.90,86.5,...,3.388000,3.666219,9500.0,23500.0,2474.0
11622,2013,Udayapur,Millet,26.90,86.5,...,3.388000,3.666219,2580.0,5000.0,1938.0
11623,2013,Udayapur,Paddy,26.90,86.5,...,3.388000,3.666219,15250.0,52850.0,3466.0
11624,2013,Udayapur,Wheat,26.90,86.5,...,3.388000,3.666219,5120.0,15826.0,3091.0

In [39]:
data.dtypes

Year                          object
District                      object
Crop                          object
Latitude                     float64
Longitude                    float64
Precipitation(mm)            float64
Surface_Pressure(kPa)        float64
Specific_Humidity(g/kg)      float64
Relative_Humidity(%)         float64
Temp(C)                      float64
Wet_Bulb_Temp(C)             float64
Max_Temp(C)                  float64
Min_Temp(C)                  float64
Earth_Skin_Temp(C)           float64
Wind_Speed_10M(m/s)          float64
Max_Wind_Speed_10M(m/s)      float64
Min_Wind_Speed_10M(m/s)      float64
Wind_Speed_50M(m/s)          float64
Max_Wind_Speed_50M(m/s)      float64
Min_Wind_Speed_50M(m/s)      float64
Temp_Range(C)                float64
Wind_Speed_10M_Range(m/s)    float64
Wind_Speed_50M_Range(m/s)    float64
Area(ha)                     float64
Production(mt)               float64
Yield(kg/ha)                 float64
dtype: object

We need to convert every value into a numeric form. We can see above that three columns 'Year', 'District' and 'Crop' are not in numeric form.<br>
We can simply convert 'Year' into a integer data type.<br>
We will be using the Longitude and Latitude of the Districts instead of their names so we can simply drop the 'District' column.<br>
We will use OneHotEncoding for the 'Crop' column.

In [40]:
#Convert 'Year' into int64 datat type.
data['Year'] = data['Year'].astype(int)
display(data)
display(data.dtypes)
# data.to_csv('hist_data.csv', index=False)

,Year,District,Crop,Latitude,Longitude,...,Wind_Speed_10M_Range(m/s),Wind_Speed_50M_Range(m/s),Area(ha),Production(mt),Yield(kg/ha)
0,1982,Achham,Barley,29.11,81.3,...,3.941562,3.969315,500.0,400.0,800.0
1,1982,Achham,Maize,29.11,81.3,...,3.941562,3.969315,2850.0,3420.0,1200.0
2,1982,Achham,Millet,29.11,81.3,...,3.941562,3.969315,850.0,940.0,1106.0
3,1982,Achham,Paddy,29.11,81.3,...,3.941562,3.969315,1930.0,2700.0,1399.0
4,1982,Achham,Wheat,29.11,81.3,...,3.941562,3.969315,3200.0,3360.0,1050.0
...,...,...,...,...,...,...,...,...,...,...,...
11620,2013,Udayapur,Barley,26.90,86.5,...,3.388000,3.666219,35.0,35.0,1000.0
11621,2013,Udayapur,Maize,26.90,86.5,...,3.388000,3.666219,9500.0,23500.0,2474.0
11622,2013,Udayapur,Millet,26.90,86.5,...,3.388000,3.666219,2580.0,5000.0,1938.0
11623,2013,Udayapur,Paddy,26.90,86.5,...,3.388000,3.666219,15250.0,52850.0,3466.0
11624,2013,Udayapur,Wheat,26.90,86.5,...,3.388000,3.666219,5120.0,15826.0,3091.0

Year                           int64
District                      object
Crop                          object
Latitude                     float64
Longitude                    float64
Precipitation(mm)            float64
Surface_Pressure(kPa)        float64
Specific_Humidity(g/kg)      float64
Relative_Humidity(%)         float64
Temp(C)                      float64
Wet_Bulb_Temp(C)             float64
Max_Temp(C)                  float64
Min_Temp(C)                  float64
Earth_Skin_Temp(C)           float64
Wind_Speed_10M(m/s)          float64
Max_Wind_Speed_10M(m/s)      float64
Min_Wind_Speed_10M(m/s)      float64
Wind_Speed_50M(m/s)          float64
Max_Wind_Speed_50M(m/s)      float64
Min_Wind_Speed_50M(m/s)      float64
Temp_Range(C)                float64
Wind_Speed_10M_Range(m/s)    float64
Wind_Speed_50M_Range(m/s)    float64
Area(ha)                     float64
Production(mt)               float64
Yield(kg/ha)                 float64
dtype: object

Before dropping the 'District' column, let us first verify that there are exactly 75 unique pairs of Latitude and Longitude.

In [41]:
#Number of districts
display('Number of unique districts:')
display(len(data['District'].unique()))

#Number of pairs of latitudes and longitudes
display('Number of unique pairs of Latitude and Longitude:')
display(data[['Latitude', 'Longitude']].apply(tuple, axis=1).nunique())

'Number of unique districts:'

75

'Number of unique pairs of Latitude and Longitude:'

105

There appears to be more number of pairs of latitude and longitude than there are districts. Let's see if there are any districts with multiple unique pairs of latitudes and longitudes.

In [42]:
district_locations = data.groupby('District')[['Latitude', 'Longitude']].apply(lambda x: set(tuple(row) for row in x.values)).to_dict()

for district, locations in district_locations.items():
    print("District:", district)
    for location in locations:
        print(location[0], location[1])
    print()

District: Achham
29.11 81.3

District: Arghakhanchi
27.9 83.2

District: Baglung
28.3 83.6
28.300000000000004 83.6

District: Baitadi
29.5 80.5

District: Bajhang
29.6 81.2

District: Bajura
29.56 81.56

District: Banke
28.1 81.7

District: Bara
27.2 85.0
27.199999999999996 85.0

District: Bardiya
28.300000000000004 81.4
28.3 81.4

District: Bhaktapur
27.699999999999996 85.5
27.7 85.5

District: Bhojpur
27.179999999999996 87.07
27.180000000000003 87.07

District: Chitwan
27.699999999999996 84.4
27.7 84.4

District: Dadeldhura
29.3 80.6
29.300000000000004 80.6

District: Dailekh
28.800000000000004 81.7
28.8 81.7

District: Dang
28.0 82.4

District: Darchula
29.9 80.6

District: Dhading
27.699999999999996 85.2
27.7 85.2

District: Dhankuta
27.0 87.3

District: Dhanusa
26.699999999999996 85.9
26.7 85.9

District: Dolakha
27.6 86.2

District: Dolpa
29.0 82.9

District: Doti
29.199999999999996 80.9
29.2 80.9

District: Gorkha
28.0 84.6

District: Gulmi
28.1 83.2

District: Humla
30.0 81.8

District: Ilam
26.9 87.9

District: Jajarkot
28.87 82.17
28.870000000000005 82.17

District: Jhapa
26.699999999999996 87.9
26.7 87.9

District: Jumla
29.300000000000004 82.3
29.3 82.3

District: Kailali
28.8 80.8
28.800000000000004 80.8

District: Kalikot
29.2 81.75
29.199999999999996 81.75

District: Kanchanpur
29.0 80.2

District: Kapilbastu
27.63 82.98
27.629999999999995 82.98

District: Kaski
28.199999999999996 84.0
28.2 84.0

District: Kathmandu
27.7 85.3
27.699999999999996 85.3

District: Kavre
27.6 85.6

District: Khotang
27.17 86.79

District: Lalitpur
27.6 85.3

District: Lamjung
28.3 84.4
28.300000000000004 84.4

District: Mahottari
26.699999999999996 85.8
26.7 85.8

District: Makwanpur
27.4 85.0

District: Manang
28.6 84.2

District: Morang
26.5 87.3

District: Mugu
29.5 82.1

District: Mustang
28.9 83.8

District: Myagdi
28.4 83.6

District: Nawalparasi
27.6 84.0

District: Nuwakot
27.8 85.2
27.800000000000004 85.2

District: Okhaldhunga
27.300000000000004 86.5
27.3 86.5

District: Palpa
27.9 83.5

District: Panchthar
27.1 87.8

District: Parbat
28.199999999999996 83.7
28.2 83.7

District: Parsa
27.239999999999995 84.78
27.240000000000002 84.78

District: Pyuthan
28.120000000000005 82.87
28.12 82.87

District: Ramechhap
27.510000000000005 86.18
27.509999999999998 86.18

District: Rasuwa
28.1 85.3

District: Rautahat
26.8 85.3
26.800000000000004 85.3

District: Rolpa
28.35 82.63

District: Rukum
28.6 82.4

District: Rupandehi
27.5 83.4

District: Salyan
28.4 82.1

District: Sankhuwasabha
27.300000000000004 87.3
27.3 87.3

District: Saptari
26.6 86.8

District: Sarlahi
26.9 85.5

District: Sindhuli
27.199999999999996 85.9
27.2 85.9

District: Sindhupalchok
27.91 85.74

District: Siraha
26.75 86.34

District: Solukhumbu
28.0 86.8

District: Sunsari
26.6 87.1

District: Surkhet
28.5 81.7

District: Syangja
28.0 83.8

District: Tanahu
28.0 84.1

District: Taplejung
27.4 87.7

District: Tehrathum
27.1 87.5

District: Udayapur
26.9 86.5

Above, we can see that some districts have two values for latitude. But the values are just different because of decimal points. Let's round the latitudes and longitudes and check again.

In [43]:
#Round latitude and longitude values
data['Latitude'] = data['Latitude'].round(2)
data['Longitude'] = data['Longitude'].round(2)

display('Number of unique pairs of Latitude and Longitude:')
display(data[['Latitude', 'Longitude']].apply(tuple, axis=1).nunique())

for district, locations in district_locations.items():
    print("District:", district)
    for location in locations:
        print(location[0], location[1])
    print()

'Number of unique pairs of Latitude and Longitude:'

75

District: Achham
29.11 81.3

District: Arghakhanchi
27.9 83.2

District: Baglung
28.3 83.6
28.300000000000004 83.6

District: Baitadi
29.5 80.5

District: Bajhang
29.6 81.2

District: Bajura
29.56 81.56

District: Banke
28.1 81.7

District: Bara
27.2 85.0
27.199999999999996 85.0

District: Bardiya
28.300000000000004 81.4
28.3 81.4

District: Bhaktapur
27.699999999999996 85.5
27.7 85.5

District: Bhojpur
27.179999999999996 87.07
27.180000000000003 87.07

District: Chitwan
27.699999999999996 84.4
27.7 84.4

District: Dadeldhura
29.3 80.6
29.300000000000004 80.6

District: Dailekh
28.800000000000004 81.7
28.8 81.7

District: Dang
28.0 82.4

District: Darchula
29.9 80.6

District: Dhading
27.699999999999996 85.2
27.7 85.2

District: Dhankuta
27.0 87.3

District: Dhanusa
26.699999999999996 85.9
26.7 85.9

District: Dolakha
27.6 86.2

District: Dolpa
29.0 82.9

District: Doti
29.199999999999996 80.9
29.2 80.9

District: Gorkha
28.0 84.6

District: Gulmi
28.1 83.2

District: Humla
30.0 81.8

District: Ilam
26.9 87.9

District: Jajarkot
28.87 82.17
28.870000000000005 82.17

District: Jhapa
26.699999999999996 87.9
26.7 87.9

District: Jumla
29.300000000000004 82.3
29.3 82.3

District: Kailali
28.8 80.8
28.800000000000004 80.8

District: Kalikot
29.2 81.75
29.199999999999996 81.75

District: Kanchanpur
29.0 80.2

District: Kapilbastu
27.63 82.98
27.629999999999995 82.98

District: Kaski
28.199999999999996 84.0
28.2 84.0

District: Kathmandu
27.7 85.3
27.699999999999996 85.3

District: Kavre
27.6 85.6

District: Khotang
27.17 86.79

District: Lalitpur
27.6 85.3

District: Lamjung
28.3 84.4
28.300000000000004 84.4

District: Mahottari
26.699999999999996 85.8
26.7 85.8

District: Makwanpur
27.4 85.0

District: Manang
28.6 84.2

District: Morang
26.5 87.3

District: Mugu
29.5 82.1

District: Mustang
28.9 83.8

District: Myagdi
28.4 83.6

District: Nawalparasi
27.6 84.0

District: Nuwakot
27.8 85.2
27.800000000000004 85.2

District: Okhaldhunga
27.300000000000004 86.5
27.3 86.5

District: Palpa
27.9 83.5

District: Panchthar
27.1 87.8

District: Parbat
28.199999999999996 83.7
28.2 83.7

District: Parsa
27.239999999999995 84.78
27.240000000000002 84.78

District: Pyuthan
28.120000000000005 82.87
28.12 82.87

District: Ramechhap
27.510000000000005 86.18
27.509999999999998 86.18

District: Rasuwa
28.1 85.3

District: Rautahat
26.8 85.3
26.800000000000004 85.3

District: Rolpa
28.35 82.63

District: Rukum
28.6 82.4

District: Rupandehi
27.5 83.4

District: Salyan
28.4 82.1

District: Sankhuwasabha
27.300000000000004 87.3
27.3 87.3

District: Saptari
26.6 86.8

District: Sarlahi
26.9 85.5

District: Sindhuli
27.199999999999996 85.9
27.2 85.9

District: Sindhupalchok
27.91 85.74

District: Siraha
26.75 86.34

District: Solukhumbu
28.0 86.8

District: Sunsari
26.6 87.1

District: Surkhet
28.5 81.7

District: Syangja
28.0 83.8

District: Tanahu
28.0 84.1

District: Taplejung
27.4 87.7

District: Tehrathum
27.1 87.5

District: Udayapur
26.9 86.5

Now that we have unique pairs of longitude and latitude for each district, we can drop the 'District' column.

In [44]:
# data.drop('District', axis=1, inplace=True)
data

,Year,District,Crop,Latitude,Longitude,...,Wind_Speed_10M_Range(m/s),Wind_Speed_50M_Range(m/s),Area(ha),Production(mt),Yield(kg/ha)
0,1982,Achham,Barley,29.11,81.3,...,3.941562,3.969315,500.0,400.0,800.0
1,1982,Achham,Maize,29.11,81.3,...,3.941562,3.969315,2850.0,3420.0,1200.0
2,1982,Achham,Millet,29.11,81.3,...,3.941562,3.969315,850.0,940.0,1106.0
3,1982,Achham,Paddy,29.11,81.3,...,3.941562,3.969315,1930.0,2700.0,1399.0
4,1982,Achham,Wheat,29.11,81.3,...,3.941562,3.969315,3200.0,3360.0,1050.0
...,...,...,...,...,...,...,...,...,...,...,...
11620,2013,Udayapur,Barley,26.90,86.5,...,3.388000,3.666219,35.0,35.0,1000.0
11621,2013,Udayapur,Maize,26.90,86.5,...,3.388000,3.666219,9500.0,23500.0,2474.0
11622,2013,Udayapur,Millet,26.90,86.5,...,3.388000,3.666219,2580.0,5000.0,1938.0
11623,2013,Udayapur,Paddy,26.90,86.5,...,3.388000,3.666219,15250.0,52850.0,3466.0
11624,2013,Udayapur,Wheat,26.90,86.5,...,3.388000,3.666219,5120.0,15826.0,3091.0

In [45]:
data.to_csv('he.csv', sep=',', index=False, encoding='utf-8')

For the 'Crop' column, let's use OneHotEncoding.

In [46]:
from sklearn.preprocessing import OneHotEncoder

data = pd.get_dummies(data, columns=['Crop'], prefix=['Crop']) #convert into one hot encoding format
data

,Year,District,Latitude,Longitude,Precipitation(mm),...,Crop_Barley,Crop_Maize,Crop_Millet,Crop_Paddy,Crop_Wheat
0,1982,Achham,29.11,81.3,665.15,...,1,0,0,0,0
1,1982,Achham,29.11,81.3,665.15,...,0,1,0,0,0
2,1982,Achham,29.11,81.3,665.15,...,0,0,1,0,0
3,1982,Achham,29.11,81.3,665.15,...,0,0,0,1,0
4,1982,Achham,29.11,81.3,665.15,...,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
11620,2013,Udayapur,26.90,86.5,1091.43,...,1,0,0,0,0
11621,2013,Udayapur,26.90,86.5,1091.43,...,0,1,0,0,0
11622,2013,Udayapur,26.90,86.5,1091.43,...,0,0,1,0,0
11623,2013,Udayapur,26.90,86.5,1091.43,...,0,0,0,1,0
11624,2013,Udayapur,26.90,86.5,1091.43,...,0,0,0,0,1

In [47]:
# Remove and re-add the 'Yield(kg/ha)' column to the end of the dataframe
dft = data.loc[:, data.columns != 'Yield(kg/ha)']
dft['Yield(kg/ha)'] = data['Yield(kg/ha)']
data = dft
data

,Year,District,Latitude,Longitude,Precipitation(mm),...,Crop_Maize,Crop_Millet,Crop_Paddy,Crop_Wheat,Yield(kg/ha)
0,1982,Achham,29.11,81.3,665.15,...,0,0,0,0,800.0
1,1982,Achham,29.11,81.3,665.15,...,1,0,0,0,1200.0
2,1982,Achham,29.11,81.3,665.15,...,0,1,0,0,1106.0
3,1982,Achham,29.11,81.3,665.15,...,0,0,1,0,1399.0
4,1982,Achham,29.11,81.3,665.15,...,0,0,0,1,1050.0
...,...,...,...,...,...,...,...,...,...,...,...
11620,2013,Udayapur,26.90,86.5,1091.43,...,0,0,0,0,1000.0
11621,2013,Udayapur,26.90,86.5,1091.43,...,1,0,0,0,2474.0
11622,2013,Udayapur,26.90,86.5,1091.43,...,0,1,0,0,1938.0
11623,2013,Udayapur,26.90,86.5,1091.43,...,0,0,1,0,3466.0
11624,2013,Udayapur,26.90,86.5,1091.43,...,0,0,0,1,3091.0

In [48]:
# Remove and re-add the 'Production(mt)' column to the end of the dataframe
dft = data.loc[:, data.columns != 'Production(mt)']
dft['Production(mt)'] = data['Production(mt)']
data = dft
data

,Year,District,Latitude,Longitude,Precipitation(mm),...,Crop_Millet,Crop_Paddy,Crop_Wheat,Yield(kg/ha),Production(mt)
0,1982,Achham,29.11,81.3,665.15,...,0,0,0,800.0,400.0
1,1982,Achham,29.11,81.3,665.15,...,0,0,0,1200.0,3420.0
2,1982,Achham,29.11,81.3,665.15,...,1,0,0,1106.0,940.0
3,1982,Achham,29.11,81.3,665.15,...,0,1,0,1399.0,2700.0
4,1982,Achham,29.11,81.3,665.15,...,0,0,1,1050.0,3360.0
...,...,...,...,...,...,...,...,...,...,...,...
11620,2013,Udayapur,26.90,86.5,1091.43,...,0,0,0,1000.0,35.0
11621,2013,Udayapur,26.90,86.5,1091.43,...,0,0,0,2474.0,23500.0
11622,2013,Udayapur,26.90,86.5,1091.43,...,1,0,0,1938.0,5000.0
11623,2013,Udayapur,26.90,86.5,1091.43,...,0,1,0,3466.0,52850.0
11624,2013,Udayapur,26.90,86.5,1091.43,...,0,0,1,3091.0,15826.0

In [49]:
#Save the final data to disk.
data.to_csv('fin_int.csv', sep=',', index=False, encoding='utf-8')